// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws349;


public class AssetReadResult extends org.jboss.test.webservice.jbws349.Result {
    protected java.lang.String id;
    protected java.lang.String body;
    
    public AssetReadResult() {
    }
    
    public AssetReadResult(java.lang.String id, java.lang.String body) {
        this.id = id;
        this.body = body;
    }
    
    public java.lang.String getId() {
        return id;
    }
    
    public void setId(java.lang.String id) {
        this.id = id;
    }
    
    public java.lang.String getBody() {
        return body;
    }
    
    public void setBody(java.lang.String body) {
        this.body = body;
    }
}
