// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws349;


public class AssetCreate extends org.jboss.test.webservice.jbws349.Event {
    protected int nextStep;
    protected java.lang.String template;
    
    public AssetCreate() {
    }
    
    public AssetCreate(java.lang.String id, int nextStep, java.lang.String template) {
        this.id = id;
        this.nextStep = nextStep;
        this.template = template;
    }
    
    public int getNextStep() {
        return nextStep;
    }
    
    public void setNextStep(int nextStep) {
        this.nextStep = nextStep;
    }
    
    public java.lang.String getTemplate() {
        return template;
    }
    
    public void setTemplate(java.lang.String template) {
        this.template = template;
    }
}
