// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws349;


public class AssetRead extends org.jboss.test.webservice.jbws349.Event {
    
    public AssetRead() {
    }
    
    public AssetRead(java.lang.String id) {
        this.id = id;
    }
}
