// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws349;


public class AssetCreateResult extends org.jboss.test.webservice.jbws349.Result {
    protected java.lang.String id;
    
    public AssetCreateResult() {
    }
    
    public AssetCreateResult(java.lang.String id) {
        this.id = id;
    }
    
    public java.lang.String getId() {
        return id;
    }
    
    public void setId(java.lang.String id) {
        this.id = id;
    }
}
