// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp;

import org.jboss.test.wsrp.core.*; 

public interface WSRP_v1_PortletManagement_PortType extends java.rmi.Remote
{
   public PortletDescriptionResponse getPortletDescription(GetPortletDescription getPortletDescription) throws
      AccessDeniedFault, InvalidHandleFault, InvalidUserCategoryFault, InconsistentParametersFault, MissingParametersFault, InvalidRegistrationFault, OperationFailedFault, java.rmi.RemoteException;

   public PortletContext clonePortlet(ClonePortlet clonePortlet) throws
      InvalidUserCategoryFault, AccessDeniedFault, OperationFailedFault, InvalidHandleFault, InvalidRegistrationFault, InconsistentParametersFault, MissingParametersFault, java.rmi.RemoteException;

   public DestroyPortletsResponse destroyPortlets(DestroyPortlets destroyPortlets) throws
      InconsistentParametersFault, MissingParametersFault, InvalidRegistrationFault, OperationFailedFault, java.rmi.RemoteException;

   public PortletContext setPortletProperties(SetPortletProperties setPortletProperties) throws
      OperationFailedFault, InvalidHandleFault, MissingParametersFault, InconsistentParametersFault, InvalidUserCategoryFault, AccessDeniedFault, InvalidRegistrationFault, java.rmi.RemoteException;

   public PropertyList getPortletProperties(GetPortletProperties getPortletProperties) throws
      InvalidHandleFault, MissingParametersFault, InvalidRegistrationFault, AccessDeniedFault, OperationFailedFault, InconsistentParametersFault, InvalidUserCategoryFault, java.rmi.RemoteException;

   public PortletPropertyDescriptionResponse getPortletPropertyDescription(GetPortletPropertyDescription getPortletPropertyDescription) throws
      MissingParametersFault, InconsistentParametersFault, InvalidUserCategoryFault, InvalidRegistrationFault, AccessDeniedFault, InvalidHandleFault, OperationFailedFault, java.rmi.RemoteException;
}
