// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp;

import javax.xml.rpc.*;

public interface WSRPService extends javax.xml.rpc.Service 
{
    public WSRP_v1_Markup_PortType getWSRPMarkupService() throws ServiceException;
    public WSRP_v1_ServiceDescription_PortType getWSRPServiceDescriptionService() throws ServiceException;
    public WSRP_v1_Registration_PortType getWSRPRegistrationService() throws ServiceException;
    public WSRP_v1_PortletManagement_PortType getWSRPPortletManagementService() throws ServiceException;
}
