// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ActiveState {
    protected java.lang.Boolean deliveryExtensionRemoved;
    protected java.lang.Boolean sharedDataSourceRemoved;
    protected java.lang.Boolean missingParameterValue;
    protected java.lang.Boolean invalidParameterValue;
    protected java.lang.Boolean unknownReportParameter;
    
    public ActiveState() {
    }
    
    public ActiveState(java.lang.Boolean deliveryExtensionRemoved, java.lang.Boolean sharedDataSourceRemoved, java.lang.Boolean missingParameterValue, java.lang.Boolean invalidParameterValue, java.lang.Boolean unknownReportParameter) {
        this.deliveryExtensionRemoved = deliveryExtensionRemoved;
        this.sharedDataSourceRemoved = sharedDataSourceRemoved;
        this.missingParameterValue = missingParameterValue;
        this.invalidParameterValue = invalidParameterValue;
        this.unknownReportParameter = unknownReportParameter;
    }
    
    public java.lang.Boolean getDeliveryExtensionRemoved() {
        return deliveryExtensionRemoved;
    }
    
    public void setDeliveryExtensionRemoved(java.lang.Boolean deliveryExtensionRemoved) {
        this.deliveryExtensionRemoved = deliveryExtensionRemoved;
    }
    
    public java.lang.Boolean getSharedDataSourceRemoved() {
        return sharedDataSourceRemoved;
    }
    
    public void setSharedDataSourceRemoved(java.lang.Boolean sharedDataSourceRemoved) {
        this.sharedDataSourceRemoved = sharedDataSourceRemoved;
    }
    
    public java.lang.Boolean getMissingParameterValue() {
        return missingParameterValue;
    }
    
    public void setMissingParameterValue(java.lang.Boolean missingParameterValue) {
        this.missingParameterValue = missingParameterValue;
    }
    
    public java.lang.Boolean getInvalidParameterValue() {
        return invalidParameterValue;
    }
    
    public void setInvalidParameterValue(java.lang.Boolean invalidParameterValue) {
        this.invalidParameterValue = invalidParameterValue;
    }
    
    public java.lang.Boolean getUnknownReportParameter() {
        return unknownReportParameter;
    }
    
    public void setUnknownReportParameter(java.lang.Boolean unknownReportParameter) {
        this.unknownReportParameter = unknownReportParameter;
    }
}
