// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ArrayOfSearchCondition {
    protected org.jboss.test.webservice.jbws718.SearchCondition[] searchCondition;
    
    public ArrayOfSearchCondition() {
    }
    
    public ArrayOfSearchCondition(org.jboss.test.webservice.jbws718.SearchCondition[] searchCondition) {
        this.searchCondition = searchCondition;
    }
    
    public org.jboss.test.webservice.jbws718.SearchCondition[] getSearchCondition() {
        return searchCondition;
    }
    
    public void setSearchCondition(org.jboss.test.webservice.jbws718.SearchCondition[] searchCondition) {
        this.searchCondition = searchCondition;
    }
}
