// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ArrayOfTask {
    protected org.jboss.test.webservice.jbws718.Task[] task;
    
    public ArrayOfTask() {
    }
    
    public ArrayOfTask(org.jboss.test.webservice.jbws718.Task[] task) {
        this.task = task;
    }
    
    public org.jboss.test.webservice.jbws718.Task[] getTask() {
        return task;
    }
    
    public void setTask(org.jboss.test.webservice.jbws718.Task[] task) {
        this.task = task;
    }
}
