// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ArrayOfRole {
    protected org.jboss.test.webservice.jbws718.Role[] role;
    
    public ArrayOfRole() {
    }
    
    public ArrayOfRole(org.jboss.test.webservice.jbws718.Role[] role) {
        this.role = role;
    }
    
    public org.jboss.test.webservice.jbws718.Role[] getRole() {
        return role;
    }
    
    public void setRole(org.jboss.test.webservice.jbws718.Role[] role) {
        this.role = role;
    }
}
