// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ArrayOfExtension {
    protected org.jboss.test.webservice.jbws718.Extension[] extension;
    
    public ArrayOfExtension() {
    }
    
    public ArrayOfExtension(org.jboss.test.webservice.jbws718.Extension[] extension) {
        this.extension = extension;
    }
    
    public org.jboss.test.webservice.jbws718.Extension[] getExtension() {
        return extension;
    }
    
    public void setExtension(org.jboss.test.webservice.jbws718.Extension[] extension) {
        this.extension = extension;
    }
}
