// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ArrayOfSubscription {
    protected org.jboss.test.webservice.jbws718.Subscription[] subscription;
    
    public ArrayOfSubscription() {
    }
    
    public ArrayOfSubscription(org.jboss.test.webservice.jbws718.Subscription[] subscription) {
        this.subscription = subscription;
    }
    
    public org.jboss.test.webservice.jbws718.Subscription[] getSubscription() {
        return subscription;
    }
    
    public void setSubscription(org.jboss.test.webservice.jbws718.Subscription[] subscription) {
        this.subscription = subscription;
    }
}
