// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ArrayOfPolicy {
    protected org.jboss.test.webservice.jbws718.Policy[] policy;
    
    public ArrayOfPolicy() {
    }
    
    public ArrayOfPolicy(org.jboss.test.webservice.jbws718.Policy[] policy) {
        this.policy = policy;
    }
    
    public org.jboss.test.webservice.jbws718.Policy[] getPolicy() {
        return policy;
    }
    
    public void setPolicy(org.jboss.test.webservice.jbws718.Policy[] policy) {
        this.policy = policy;
    }
}
