// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ArrayOfWarning {
    protected org.jboss.test.webservice.jbws718.Warning[] warning;
    
    public ArrayOfWarning() {
    }
    
    public ArrayOfWarning(org.jboss.test.webservice.jbws718.Warning[] warning) {
        this.warning = warning;
    }
    
    public org.jboss.test.webservice.jbws718.Warning[] getWarning() {
        return warning;
    }
    
    public void setWarning(org.jboss.test.webservice.jbws718.Warning[] warning) {
        this.warning = warning;
    }
}
