// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ArrayOfValidValue1 {
    protected org.jboss.test.webservice.jbws718.ValidValue[] value;
    
    public ArrayOfValidValue1() {
    }
    
    public ArrayOfValidValue1(org.jboss.test.webservice.jbws718.ValidValue[] value) {
        this.value = value;
    }
    
    public org.jboss.test.webservice.jbws718.ValidValue[] getValue() {
        return value;
    }
    
    public void setValue(org.jboss.test.webservice.jbws718.ValidValue[] value) {
        this.value = value;
    }
}
