// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ArrayOfString3 {
    protected java.lang.String[] operation;
    
    public ArrayOfString3() {
    }
    
    public ArrayOfString3(java.lang.String[] operation) {
        this.operation = operation;
    }
    
    public java.lang.String[] getOperation() {
        return operation;
    }
    
    public void setOperation(java.lang.String[] operation) {
        this.operation = operation;
    }
}
