// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ArrayOfEvent {
    protected org.jboss.test.webservice.jbws718.Event[] event;
    
    public ArrayOfEvent() {
    }
    
    public ArrayOfEvent(org.jboss.test.webservice.jbws718.Event[] event) {
        this.event = event;
    }
    
    public org.jboss.test.webservice.jbws718.Event[] getEvent() {
        return event;
    }
    
    public void setEvent(org.jboss.test.webservice.jbws718.Event[] event) {
        this.event = event;
    }
}
