// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ArrayOfProperty {
    protected org.jboss.test.webservice.jbws718.Property[] property;
    
    public ArrayOfProperty() {
    }
    
    public ArrayOfProperty(org.jboss.test.webservice.jbws718.Property[] property) {
        this.property = property;
    }
    
    public org.jboss.test.webservice.jbws718.Property[] getProperty() {
        return property;
    }
    
    public void setProperty(org.jboss.test.webservice.jbws718.Property[] property) {
        this.property = property;
    }
}
