// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ArrayOfDataSourcePrompt {
    protected org.jboss.test.webservice.jbws718.DataSourcePrompt[] dataSourcePrompt;
    
    public ArrayOfDataSourcePrompt() {
    }
    
    public ArrayOfDataSourcePrompt(org.jboss.test.webservice.jbws718.DataSourcePrompt[] dataSourcePrompt) {
        this.dataSourcePrompt = dataSourcePrompt;
    }
    
    public org.jboss.test.webservice.jbws718.DataSourcePrompt[] getDataSourcePrompt() {
        return dataSourcePrompt;
    }
    
    public void setDataSourcePrompt(org.jboss.test.webservice.jbws718.DataSourcePrompt[] dataSourcePrompt) {
        this.dataSourcePrompt = dataSourcePrompt;
    }
}
