// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ArrayOfParameterValueOrFieldReference {
    protected org.jboss.test.webservice.jbws718.ParameterValueOrFieldReference[] parameterValueOrFieldReference;
    
    public ArrayOfParameterValueOrFieldReference() {
    }
    
    public ArrayOfParameterValueOrFieldReference(org.jboss.test.webservice.jbws718.ParameterValueOrFieldReference[] parameterValueOrFieldReference) {
        this.parameterValueOrFieldReference = parameterValueOrFieldReference;
    }
    
    public org.jboss.test.webservice.jbws718.ParameterValueOrFieldReference[] getParameterValueOrFieldReference() {
        return parameterValueOrFieldReference;
    }
    
    public void setParameterValueOrFieldReference(org.jboss.test.webservice.jbws718.ParameterValueOrFieldReference[] parameterValueOrFieldReference) {
        this.parameterValueOrFieldReference = parameterValueOrFieldReference;
    }
}
