// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ArrayOfExtensionParameter {
    protected org.jboss.test.webservice.jbws718.ExtensionParameter[] extensionParameter;
    
    public ArrayOfExtensionParameter() {
    }
    
    public ArrayOfExtensionParameter(org.jboss.test.webservice.jbws718.ExtensionParameter[] extensionParameter) {
        this.extensionParameter = extensionParameter;
    }
    
    public org.jboss.test.webservice.jbws718.ExtensionParameter[] getExtensionParameter() {
        return extensionParameter;
    }
    
    public void setExtensionParameter(org.jboss.test.webservice.jbws718.ExtensionParameter[] extensionParameter) {
        this.extensionParameter = extensionParameter;
    }
}
