// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ArrayOfReportParameter {
    protected org.jboss.test.webservice.jbws718.ReportParameter[] reportParameter;
    
    public ArrayOfReportParameter() {
    }
    
    public ArrayOfReportParameter(org.jboss.test.webservice.jbws718.ReportParameter[] reportParameter) {
        this.reportParameter = reportParameter;
    }
    
    public org.jboss.test.webservice.jbws718.ReportParameter[] getReportParameter() {
        return reportParameter;
    }
    
    public void setReportParameter(org.jboss.test.webservice.jbws718.ReportParameter[] reportParameter) {
        this.reportParameter = reportParameter;
    }
}
