// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ArrayOfReportHistorySnapshot {
    protected org.jboss.test.webservice.jbws718.ReportHistorySnapshot[] reportHistorySnapshot;
    
    public ArrayOfReportHistorySnapshot() {
    }
    
    public ArrayOfReportHistorySnapshot(org.jboss.test.webservice.jbws718.ReportHistorySnapshot[] reportHistorySnapshot) {
        this.reportHistorySnapshot = reportHistorySnapshot;
    }
    
    public org.jboss.test.webservice.jbws718.ReportHistorySnapshot[] getReportHistorySnapshot() {
        return reportHistorySnapshot;
    }
    
    public void setReportHistorySnapshot(org.jboss.test.webservice.jbws718.ReportHistorySnapshot[] reportHistorySnapshot) {
        this.reportHistorySnapshot = reportHistorySnapshot;
    }
}
