// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ArrayOfParameterValue {
    protected org.jboss.test.webservice.jbws718.ParameterValue[] parameterValue;
    
    public ArrayOfParameterValue() {
    }
    
    public ArrayOfParameterValue(org.jboss.test.webservice.jbws718.ParameterValue[] parameterValue) {
        this.parameterValue = parameterValue;
    }
    
    public org.jboss.test.webservice.jbws718.ParameterValue[] getParameterValue() {
        return parameterValue;
    }
    
    public void setParameterValue(org.jboss.test.webservice.jbws718.ParameterValue[] parameterValue) {
        this.parameterValue = parameterValue;
    }
}
