// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ArrayOfJob {
    protected org.jboss.test.webservice.jbws718.Job[] job;
    
    public ArrayOfJob() {
    }
    
    public ArrayOfJob(org.jboss.test.webservice.jbws718.Job[] job) {
        this.job = job;
    }
    
    public org.jboss.test.webservice.jbws718.Job[] getJob() {
        return job;
    }
    
    public void setJob(org.jboss.test.webservice.jbws718.Job[] job) {
        this.job = job;
    }
}
