// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ArrayOfDataSourceCredentials {
    protected org.jboss.test.webservice.jbws718.DataSourceCredentials[] dataSourceCredentials;
    
    public ArrayOfDataSourceCredentials() {
    }
    
    public ArrayOfDataSourceCredentials(org.jboss.test.webservice.jbws718.DataSourceCredentials[] dataSourceCredentials) {
        this.dataSourceCredentials = dataSourceCredentials;
    }
    
    public org.jboss.test.webservice.jbws718.DataSourceCredentials[] getDataSourceCredentials() {
        return dataSourceCredentials;
    }
    
    public void setDataSourceCredentials(org.jboss.test.webservice.jbws718.DataSourceCredentials[] dataSourceCredentials) {
        this.dataSourceCredentials = dataSourceCredentials;
    }
}
