// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ArrayOfSchedule {
    protected org.jboss.test.webservice.jbws718.Schedule[] schedule;
    
    public ArrayOfSchedule() {
    }
    
    public ArrayOfSchedule(org.jboss.test.webservice.jbws718.Schedule[] schedule) {
        this.schedule = schedule;
    }
    
    public org.jboss.test.webservice.jbws718.Schedule[] getSchedule() {
        return schedule;
    }
    
    public void setSchedule(org.jboss.test.webservice.jbws718.Schedule[] schedule) {
        this.schedule = schedule;
    }
}
