// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ArrayOfDataSource {
    protected javax.xml.soap.SOAPElement[] dataSource;
    
    public ArrayOfDataSource() {
    }
    
    public ArrayOfDataSource(javax.xml.soap.SOAPElement[] dataSource) {
        this.dataSource = dataSource;
    }
    
    public javax.xml.soap.SOAPElement[] getDataSource() {
        return dataSource;
    }
    
    public void setDataSource(javax.xml.soap.SOAPElement[] dataSource) {
        this.dataSource = dataSource;
    }
}
