// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ArrayOfField {
    protected org.jboss.test.webservice.jbws718.Field[] field;
    
    public ArrayOfField() {
    }
    
    public ArrayOfField(org.jboss.test.webservice.jbws718.Field[] field) {
        this.field = field;
    }
    
    public org.jboss.test.webservice.jbws718.Field[] getField() {
        return field;
    }
    
    public void setField(org.jboss.test.webservice.jbws718.Field[] field) {
        this.field = field;
    }
}
