// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ArrayOfString1 {
    protected java.lang.String[] dependency;
    
    public ArrayOfString1() {
    }
    
    public ArrayOfString1(java.lang.String[] dependency) {
        this.dependency = dependency;
    }
    
    public java.lang.String[] getDependency() {
        return dependency;
    }
    
    public void setDependency(java.lang.String[] dependency) {
        this.dependency = dependency;
    }
}
