// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class CancelJobResponse {
    protected boolean cancelJobResult;
    
    public CancelJobResponse() {
    }
    
    public CancelJobResponse(boolean cancelJobResult) {
        this.cancelJobResult = cancelJobResult;
    }
    
    public boolean isCancelJobResult() {
        return cancelJobResult;
    }
    
    public void setCancelJobResult(boolean cancelJobResult) {
        this.cancelJobResult = cancelJobResult;
    }
}
