// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class CancelJob {
    protected java.lang.String jobID;
    
    public CancelJob() {
    }
    
    public CancelJob(java.lang.String jobID) {
        this.jobID = jobID;
    }
    
    public java.lang.String getJobID() {
        return jobID;
    }
    
    public void setJobID(java.lang.String jobID) {
        this.jobID = jobID;
    }
}
