// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class CatalogItem {
    protected java.lang.String ID;
    protected java.lang.String name;
    protected java.lang.String path;
    protected java.lang.String virtualPath;
    protected org.jboss.test.webservice.jbws718.ItemTypeEnum type;
    protected java.lang.Integer size;
    protected java.lang.String description;
    protected java.lang.Boolean hidden;
    protected java.util.Calendar creationDate;
    protected java.util.Calendar modifiedDate;
    protected java.lang.String createdBy;
    protected java.lang.String modifiedBy;
    protected java.lang.String mimeType;
    protected java.util.Calendar executionDate;
    
    public CatalogItem() {
    }
    
    public CatalogItem(java.lang.String ID, java.lang.String name, java.lang.String path, java.lang.String virtualPath, org.jboss.test.webservice.jbws718.ItemTypeEnum type, java.lang.Integer size, java.lang.String description, java.lang.Boolean hidden, java.util.Calendar creationDate, java.util.Calendar modifiedDate, java.lang.String createdBy, java.lang.String modifiedBy, java.lang.String mimeType, java.util.Calendar executionDate) {
        this.ID = ID;
        this.name = name;
        this.path = path;
        this.virtualPath = virtualPath;
        this.type = type;
        this.size = size;
        this.description = description;
        this.hidden = hidden;
        this.creationDate = creationDate;
        this.modifiedDate = modifiedDate;
        this.createdBy = createdBy;
        this.modifiedBy = modifiedBy;
        this.mimeType = mimeType;
        this.executionDate = executionDate;
    }
    
    public java.lang.String getID() {
        return ID;
    }
    
    public void setID(java.lang.String ID) {
        this.ID = ID;
    }
    
    public java.lang.String getName() {
        return name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public java.lang.String getPath() {
        return path;
    }
    
    public void setPath(java.lang.String path) {
        this.path = path;
    }
    
    public java.lang.String getVirtualPath() {
        return virtualPath;
    }
    
    public void setVirtualPath(java.lang.String virtualPath) {
        this.virtualPath = virtualPath;
    }
    
    public org.jboss.test.webservice.jbws718.ItemTypeEnum getType() {
        return type;
    }
    
    public void setType(org.jboss.test.webservice.jbws718.ItemTypeEnum type) {
        this.type = type;
    }
    
    public java.lang.Integer getSize() {
        return size;
    }
    
    public void setSize(java.lang.Integer size) {
        this.size = size;
    }
    
    public java.lang.String getDescription() {
        return description;
    }
    
    public void setDescription(java.lang.String description) {
        this.description = description;
    }
    
    public java.lang.Boolean getHidden() {
        return hidden;
    }
    
    public void setHidden(java.lang.Boolean hidden) {
        this.hidden = hidden;
    }
    
    public java.util.Calendar getCreationDate() {
        return creationDate;
    }
    
    public void setCreationDate(java.util.Calendar creationDate) {
        this.creationDate = creationDate;
    }
    
    public java.util.Calendar getModifiedDate() {
        return modifiedDate;
    }
    
    public void setModifiedDate(java.util.Calendar modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    
    public java.lang.String getCreatedBy() {
        return createdBy;
    }
    
    public void setCreatedBy(java.lang.String createdBy) {
        this.createdBy = createdBy;
    }
    
    public java.lang.String getModifiedBy() {
        return modifiedBy;
    }
    
    public void setModifiedBy(java.lang.String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    
    public java.lang.String getMimeType() {
        return mimeType;
    }
    
    public void setMimeType(java.lang.String mimeType) {
        this.mimeType = mimeType;
    }
    
    public java.util.Calendar getExecutionDate() {
        return executionDate;
    }
    
    public void setExecutionDate(java.util.Calendar executionDate) {
        this.executionDate = executionDate;
    }
}
