// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


import java.util.Map;
import java.util.HashMap;

public class ConditionEnum {
    private java.lang.String value;
    private static java.util.Map valueMap = new HashMap();
    public static final java.lang.String _ContainsString = "Contains";
    public static final java.lang.String _EqualsString = "Equals";
    
    public static final java.lang.String _Contains = new java.lang.String(_ContainsString);
    public static final java.lang.String _Equals = new java.lang.String(_EqualsString);
    
    public static final ConditionEnum Contains = new ConditionEnum(_Contains);
    public static final ConditionEnum Equals = new ConditionEnum(_Equals);
    
    protected ConditionEnum(java.lang.String value) {
        this.value = value;
        valueMap.put(this.toString(), this);
    }
    
    public java.lang.String getValue() {
        return value;
    }
    
    public static ConditionEnum fromValue(java.lang.String value)
        throws java.lang.IllegalStateException {
        if (Contains.value.equals(value)) {
            return Contains;
        } else if (Equals.value.equals(value)) {
            return Equals;
        }
        throw new java.lang.IllegalArgumentException();
    }
    
    public static ConditionEnum fromString(java.lang.String value)
        throws java.lang.IllegalStateException {
        ConditionEnum ret = (ConditionEnum)valueMap.get(value);
        if (ret != null) {
            return ret;
        }
        if (value.equals(_ContainsString)) {
            return Contains;
        } else if (value.equals(_EqualsString)) {
            return Equals;
        }
        throw new IllegalArgumentException();
    }
    
    public java.lang.String toString() {
        return value.toString();
    }
    
    private java.lang.Object readResolve()
        throws java.io.ObjectStreamException {
        return fromValue(getValue());
    }
    
    public boolean equals(java.lang.Object obj) {
        if (!(obj instanceof ConditionEnum)) {
            return false;
        }
        return ((ConditionEnum)obj).value.equals(value);
    }
    
    public int hashCode() {
        return value.hashCode();
    }
}
