// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class CreateRole {
    protected java.lang.String name;
    protected java.lang.String description;
    protected org.jboss.test.webservice.jbws718.ArrayOfTask tasks;
    
    public CreateRole() {
    }
    
    public CreateRole(java.lang.String name, java.lang.String description, org.jboss.test.webservice.jbws718.ArrayOfTask tasks) {
        this.name = name;
        this.description = description;
        this.tasks = tasks;
    }
    
    public java.lang.String getName() {
        return name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public java.lang.String getDescription() {
        return description;
    }
    
    public void setDescription(java.lang.String description) {
        this.description = description;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfTask getTasks() {
        return tasks;
    }
    
    public void setTasks(org.jboss.test.webservice.jbws718.ArrayOfTask tasks) {
        this.tasks = tasks;
    }
}
