// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class CreateLinkedReport {
    protected java.lang.String report;
    protected java.lang.String parent;
    protected java.lang.String link;
    protected org.jboss.test.webservice.jbws718.ArrayOfProperty properties;
    
    public CreateLinkedReport() {
    }
    
    public CreateLinkedReport(java.lang.String report, java.lang.String parent, java.lang.String link, org.jboss.test.webservice.jbws718.ArrayOfProperty properties) {
        this.report = report;
        this.parent = parent;
        this.link = link;
        this.properties = properties;
    }
    
    public java.lang.String getReport() {
        return report;
    }
    
    public void setReport(java.lang.String report) {
        this.report = report;
    }
    
    public java.lang.String getParent() {
        return parent;
    }
    
    public void setParent(java.lang.String parent) {
        this.parent = parent;
    }
    
    public java.lang.String getLink() {
        return link;
    }
    
    public void setLink(java.lang.String link) {
        this.link = link;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfProperty getProperties() {
        return properties;
    }
    
    public void setProperties(org.jboss.test.webservice.jbws718.ArrayOfProperty properties) {
        this.properties = properties;
    }
}
