// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class CreateFolder {
    protected java.lang.String folder;
    protected java.lang.String parent;
    protected org.jboss.test.webservice.jbws718.ArrayOfProperty properties;
    
    public CreateFolder() {
    }
    
    public CreateFolder(java.lang.String folder, java.lang.String parent, org.jboss.test.webservice.jbws718.ArrayOfProperty properties) {
        this.folder = folder;
        this.parent = parent;
        this.properties = properties;
    }
    
    public java.lang.String getFolder() {
        return folder;
    }
    
    public void setFolder(java.lang.String folder) {
        this.folder = folder;
    }
    
    public java.lang.String getParent() {
        return parent;
    }
    
    public void setParent(java.lang.String parent) {
        this.parent = parent;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfProperty getProperties() {
        return properties;
    }
    
    public void setProperties(org.jboss.test.webservice.jbws718.ArrayOfProperty properties) {
        this.properties = properties;
    }
}
