// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class CreateSchedule {
    protected java.lang.String name;
    protected javax.xml.soap.SOAPElement scheduleDefinition;
    
    public CreateSchedule() {
    }
    
    public CreateSchedule(java.lang.String name, javax.xml.soap.SOAPElement scheduleDefinition) {
        this.name = name;
        this.scheduleDefinition = scheduleDefinition;
    }
    
    public java.lang.String getName() {
        return name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public javax.xml.soap.SOAPElement getScheduleDefinition() {
        return scheduleDefinition;
    }
    
    public void setScheduleDefinition(javax.xml.soap.SOAPElement scheduleDefinition) {
        this.scheduleDefinition = scheduleDefinition;
    }
}
