// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class CreateReport {
    protected java.lang.String report;
    protected java.lang.String parent;
    protected boolean overwrite;
    protected byte[] definition;
    protected org.jboss.test.webservice.jbws718.ArrayOfProperty properties;
    
    public CreateReport() {
    }
    
    public CreateReport(java.lang.String report, java.lang.String parent, boolean overwrite, byte[] definition, org.jboss.test.webservice.jbws718.ArrayOfProperty properties) {
        this.report = report;
        this.parent = parent;
        this.overwrite = overwrite;
        this.definition = definition;
        this.properties = properties;
    }
    
    public java.lang.String getReport() {
        return report;
    }
    
    public void setReport(java.lang.String report) {
        this.report = report;
    }
    
    public java.lang.String getParent() {
        return parent;
    }
    
    public void setParent(java.lang.String parent) {
        this.parent = parent;
    }
    
    public boolean isOverwrite() {
        return overwrite;
    }
    
    public void setOverwrite(boolean overwrite) {
        this.overwrite = overwrite;
    }
    
    public byte[] getDefinition() {
        return definition;
    }
    
    public void setDefinition(byte[] definition) {
        this.definition = definition;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfProperty getProperties() {
        return properties;
    }
    
    public void setProperties(org.jboss.test.webservice.jbws718.ArrayOfProperty properties) {
        this.properties = properties;
    }
}
