// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class CreateDataSource {
    protected java.lang.String dataSource;
    protected java.lang.String parent;
    protected boolean overwrite;
    protected org.jboss.test.webservice.jbws718.DataSourceDefinition definition;
    protected org.jboss.test.webservice.jbws718.ArrayOfProperty properties;
    
    public CreateDataSource() {
    }
    
    public CreateDataSource(java.lang.String dataSource, java.lang.String parent, boolean overwrite, org.jboss.test.webservice.jbws718.DataSourceDefinition definition, org.jboss.test.webservice.jbws718.ArrayOfProperty properties) {
        this.dataSource = dataSource;
        this.parent = parent;
        this.overwrite = overwrite;
        this.definition = definition;
        this.properties = properties;
    }
    
    public java.lang.String getDataSource() {
        return dataSource;
    }
    
    public void setDataSource(java.lang.String dataSource) {
        this.dataSource = dataSource;
    }
    
    public java.lang.String getParent() {
        return parent;
    }
    
    public void setParent(java.lang.String parent) {
        this.parent = parent;
    }
    
    public boolean isOverwrite() {
        return overwrite;
    }
    
    public void setOverwrite(boolean overwrite) {
        this.overwrite = overwrite;
    }
    
    public org.jboss.test.webservice.jbws718.DataSourceDefinition getDefinition() {
        return definition;
    }
    
    public void setDefinition(org.jboss.test.webservice.jbws718.DataSourceDefinition definition) {
        this.definition = definition;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfProperty getProperties() {
        return properties;
    }
    
    public void setProperties(org.jboss.test.webservice.jbws718.ArrayOfProperty properties) {
        this.properties = properties;
    }
}
