// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class CreateReportResponse {
    protected org.jboss.test.webservice.jbws718.ArrayOfWarning warnings;
    
    public CreateReportResponse() {
    }
    
    public CreateReportResponse(org.jboss.test.webservice.jbws718.ArrayOfWarning warnings) {
        this.warnings = warnings;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfWarning getWarnings() {
        return warnings;
    }
    
    public void setWarnings(org.jboss.test.webservice.jbws718.ArrayOfWarning warnings) {
        this.warnings = warnings;
    }
}
