// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class CreateSubscriptionResponse {
    protected java.lang.String subscriptionID;
    
    public CreateSubscriptionResponse() {
    }
    
    public CreateSubscriptionResponse(java.lang.String subscriptionID) {
        this.subscriptionID = subscriptionID;
    }
    
    public java.lang.String getSubscriptionID() {
        return subscriptionID;
    }
    
    public void setSubscriptionID(java.lang.String subscriptionID) {
        this.subscriptionID = subscriptionID;
    }
}
