// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class CreateBatchResponse {
    protected java.lang.String batchID;
    
    public CreateBatchResponse() {
    }
    
    public CreateBatchResponse(java.lang.String batchID) {
        this.batchID = batchID;
    }
    
    public java.lang.String getBatchID() {
        return batchID;
    }
    
    public void setBatchID(java.lang.String batchID) {
        this.batchID = batchID;
    }
}
