// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class CreateResource {
    protected java.lang.String resource;
    protected java.lang.String parent;
    protected boolean overwrite;
    protected byte[] contents;
    protected java.lang.String mimeType;
    protected org.jboss.test.webservice.jbws718.ArrayOfProperty properties;
    
    public CreateResource() {
    }
    
    public CreateResource(java.lang.String resource, java.lang.String parent, boolean overwrite, byte[] contents, java.lang.String mimeType, org.jboss.test.webservice.jbws718.ArrayOfProperty properties) {
        this.resource = resource;
        this.parent = parent;
        this.overwrite = overwrite;
        this.contents = contents;
        this.mimeType = mimeType;
        this.properties = properties;
    }
    
    public java.lang.String getResource() {
        return resource;
    }
    
    public void setResource(java.lang.String resource) {
        this.resource = resource;
    }
    
    public java.lang.String getParent() {
        return parent;
    }
    
    public void setParent(java.lang.String parent) {
        this.parent = parent;
    }
    
    public boolean isOverwrite() {
        return overwrite;
    }
    
    public void setOverwrite(boolean overwrite) {
        this.overwrite = overwrite;
    }
    
    public byte[] getContents() {
        return contents;
    }
    
    public void setContents(byte[] contents) {
        this.contents = contents;
    }
    
    public java.lang.String getMimeType() {
        return mimeType;
    }
    
    public void setMimeType(java.lang.String mimeType) {
        this.mimeType = mimeType;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfProperty getProperties() {
        return properties;
    }
    
    public void setProperties(org.jboss.test.webservice.jbws718.ArrayOfProperty properties) {
        this.properties = properties;
    }
}
