// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class DataSourcePrompt {
    protected java.lang.String name;
    protected java.lang.String dataSourceID;
    protected java.lang.String prompt;
    
    public DataSourcePrompt() {
    }
    
    public DataSourcePrompt(java.lang.String name, java.lang.String dataSourceID, java.lang.String prompt) {
        this.name = name;
        this.dataSourceID = dataSourceID;
        this.prompt = prompt;
    }
    
    public java.lang.String getName() {
        return name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public java.lang.String getDataSourceID() {
        return dataSourceID;
    }
    
    public void setDataSourceID(java.lang.String dataSourceID) {
        this.dataSourceID = dataSourceID;
    }
    
    public java.lang.String getPrompt() {
        return prompt;
    }
    
    public void setPrompt(java.lang.String prompt) {
        this.prompt = prompt;
    }
}
