// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class DataSourceDefinition extends org.jboss.test.webservice.jbws718.DataSourceDefinitionOrReference {
    protected java.lang.String extension;
    protected java.lang.String connectString;
    protected org.jboss.test.webservice.jbws718.CredentialRetrievalEnum credentialRetrieval;
    protected boolean windowsCredentials;
    protected java.lang.Boolean impersonateUser;
    protected java.lang.String prompt;
    protected java.lang.String userName;
    protected java.lang.String password;
    protected java.lang.Boolean enabled;
    
    public DataSourceDefinition() {
    }
    
    public DataSourceDefinition(java.lang.String extension, java.lang.String connectString, org.jboss.test.webservice.jbws718.CredentialRetrievalEnum credentialRetrieval, boolean windowsCredentials, java.lang.Boolean impersonateUser, java.lang.String prompt, java.lang.String userName, java.lang.String password, java.lang.Boolean enabled) {
        this.extension = extension;
        this.connectString = connectString;
        this.credentialRetrieval = credentialRetrieval;
        this.windowsCredentials = windowsCredentials;
        this.impersonateUser = impersonateUser;
        this.prompt = prompt;
        this.userName = userName;
        this.password = password;
        this.enabled = enabled;
    }
    
    public java.lang.String getExtension() {
        return extension;
    }
    
    public void setExtension(java.lang.String extension) {
        this.extension = extension;
    }
    
    public java.lang.String getConnectString() {
        return connectString;
    }
    
    public void setConnectString(java.lang.String connectString) {
        this.connectString = connectString;
    }
    
    public org.jboss.test.webservice.jbws718.CredentialRetrievalEnum getCredentialRetrieval() {
        return credentialRetrieval;
    }
    
    public void setCredentialRetrieval(org.jboss.test.webservice.jbws718.CredentialRetrievalEnum credentialRetrieval) {
        this.credentialRetrieval = credentialRetrieval;
    }
    
    public boolean isWindowsCredentials() {
        return windowsCredentials;
    }
    
    public void setWindowsCredentials(boolean windowsCredentials) {
        this.windowsCredentials = windowsCredentials;
    }
    
    public java.lang.Boolean getImpersonateUser() {
        return impersonateUser;
    }
    
    public void setImpersonateUser(java.lang.Boolean impersonateUser) {
        this.impersonateUser = impersonateUser;
    }
    
    public java.lang.String getPrompt() {
        return prompt;
    }
    
    public void setPrompt(java.lang.String prompt) {
        this.prompt = prompt;
    }
    
    public java.lang.String getUserName() {
        return userName;
    }
    
    public void setUserName(java.lang.String userName) {
        this.userName = userName;
    }
    
    public java.lang.String getPassword() {
        return password;
    }
    
    public void setPassword(java.lang.String password) {
        this.password = password;
    }
    
    public java.lang.Boolean getEnabled() {
        return enabled;
    }
    
    public void setEnabled(java.lang.Boolean enabled) {
        this.enabled = enabled;
    }
}
