// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class DeleteItem {
    protected java.lang.String item;
    
    public DeleteItem() {
    }
    
    public DeleteItem(java.lang.String item) {
        this.item = item;
    }
    
    public java.lang.String getItem() {
        return item;
    }
    
    public void setItem(java.lang.String item) {
        this.item = item;
    }
}
