// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class DeleteReportHistorySnapshot {
    protected java.lang.String report;
    protected java.lang.String historyID;
    
    public DeleteReportHistorySnapshot() {
    }
    
    public DeleteReportHistorySnapshot(java.lang.String report, java.lang.String historyID) {
        this.report = report;
        this.historyID = historyID;
    }
    
    public java.lang.String getReport() {
        return report;
    }
    
    public void setReport(java.lang.String report) {
        this.report = report;
    }
    
    public java.lang.String getHistoryID() {
        return historyID;
    }
    
    public void setHistoryID(java.lang.String historyID) {
        this.historyID = historyID;
    }
}
