// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class DisableDataSource {
    protected java.lang.String dataSource;
    
    public DisableDataSource() {
    }
    
    public DisableDataSource(java.lang.String dataSource) {
        this.dataSource = dataSource;
    }
    
    public java.lang.String getDataSource() {
        return dataSource;
    }
    
    public void setDataSource(java.lang.String dataSource) {
        this.dataSource = dataSource;
    }
}
