// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ExtensionSettings {
    protected java.lang.String extension;
    protected javax.xml.soap.SOAPElement parameterValues;
    
    public ExtensionSettings() {
    }
    
    public ExtensionSettings(java.lang.String extension, javax.xml.soap.SOAPElement parameterValues) {
        this.extension = extension;
        this.parameterValues = parameterValues;
    }
    
    public java.lang.String getExtension() {
        return extension;
    }
    
    public void setExtension(java.lang.String extension) {
        this.extension = extension;
    }
    
    public javax.xml.soap.SOAPElement getParameterValues() {
        return parameterValues;
    }
    
    public void setParameterValues(javax.xml.soap.SOAPElement parameterValues) {
        this.parameterValues = parameterValues;
    }
}
