// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class Extension {
    protected org.jboss.test.webservice.jbws718.ExtensionTypeEnum extensionType;
    protected java.lang.String name;
    protected java.lang.String localizedName;
    protected boolean visible;
    
    public Extension() {
    }
    
    public Extension(org.jboss.test.webservice.jbws718.ExtensionTypeEnum extensionType, java.lang.String name, java.lang.String localizedName, boolean visible) {
        this.extensionType = extensionType;
        this.name = name;
        this.localizedName = localizedName;
        this.visible = visible;
    }
    
    public org.jboss.test.webservice.jbws718.ExtensionTypeEnum getExtensionType() {
        return extensionType;
    }
    
    public void setExtensionType(org.jboss.test.webservice.jbws718.ExtensionTypeEnum extensionType) {
        this.extensionType = extensionType;
    }
    
    public java.lang.String getName() {
        return name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public java.lang.String getLocalizedName() {
        return localizedName;
    }
    
    public void setLocalizedName(java.lang.String localizedName) {
        this.localizedName = localizedName;
    }
    
    public boolean isVisible() {
        return visible;
    }
    
    public void setVisible(boolean visible) {
        this.visible = visible;
    }
}
