// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


import java.util.Map;
import java.util.HashMap;

public class ExtensionTypeEnum {
    private java.lang.String value;
    private static java.util.Map valueMap = new HashMap();
    public static final java.lang.String _DeliveryString = "Delivery";
    public static final java.lang.String _RenderString = "Render";
    public static final java.lang.String _DataString = "Data";
    public static final java.lang.String _AllString = "All";
    
    public static final java.lang.String _Delivery = new java.lang.String(_DeliveryString);
    public static final java.lang.String _Render = new java.lang.String(_RenderString);
    public static final java.lang.String _Data = new java.lang.String(_DataString);
    public static final java.lang.String _All = new java.lang.String(_AllString);
    
    public static final ExtensionTypeEnum Delivery = new ExtensionTypeEnum(_Delivery);
    public static final ExtensionTypeEnum Render = new ExtensionTypeEnum(_Render);
    public static final ExtensionTypeEnum Data = new ExtensionTypeEnum(_Data);
    public static final ExtensionTypeEnum All = new ExtensionTypeEnum(_All);
    
    protected ExtensionTypeEnum(java.lang.String value) {
        this.value = value;
        valueMap.put(this.toString(), this);
    }
    
    public java.lang.String getValue() {
        return value;
    }
    
    public static ExtensionTypeEnum fromValue(java.lang.String value)
        throws java.lang.IllegalStateException {
        if (Delivery.value.equals(value)) {
            return Delivery;
        } else if (Render.value.equals(value)) {
            return Render;
        } else if (Data.value.equals(value)) {
            return Data;
        } else if (All.value.equals(value)) {
            return All;
        }
        throw new java.lang.IllegalArgumentException();
    }
    
    public static ExtensionTypeEnum fromString(java.lang.String value)
        throws java.lang.IllegalStateException {
        ExtensionTypeEnum ret = (ExtensionTypeEnum)valueMap.get(value);
        if (ret != null) {
            return ret;
        }
        if (value.equals(_DeliveryString)) {
            return Delivery;
        } else if (value.equals(_RenderString)) {
            return Render;
        } else if (value.equals(_DataString)) {
            return Data;
        } else if (value.equals(_AllString)) {
            return All;
        }
        throw new IllegalArgumentException();
    }
    
    public java.lang.String toString() {
        return value.toString();
    }
    
    private java.lang.Object readResolve()
        throws java.io.ObjectStreamException {
        return fromValue(getValue());
    }
    
    public boolean equals(java.lang.Object obj) {
        if (!(obj instanceof ExtensionTypeEnum)) {
            return false;
        }
        return ((ExtensionTypeEnum)obj).value.equals(value);
    }
    
    public int hashCode() {
        return value.hashCode();
    }
}
