// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class Field {
    protected java.lang.String alias;
    protected java.lang.String name;
    
    public Field() {
    }
    
    public Field(java.lang.String alias, java.lang.String name) {
        this.alias = alias;
        this.name = name;
    }
    
    public java.lang.String getAlias() {
        return alias;
    }
    
    public void setAlias(java.lang.String alias) {
        this.alias = alias;
    }
    
    public java.lang.String getName() {
        return name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
}
