// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class FindItems {
    protected java.lang.String folder;
    protected org.jboss.test.webservice.jbws718.BooleanOperatorEnum booleanOperator;
    protected org.jboss.test.webservice.jbws718.ArrayOfSearchCondition conditions;
    
    public FindItems() {
    }
    
    public FindItems(java.lang.String folder, org.jboss.test.webservice.jbws718.BooleanOperatorEnum booleanOperator, org.jboss.test.webservice.jbws718.ArrayOfSearchCondition conditions) {
        this.folder = folder;
        this.booleanOperator = booleanOperator;
        this.conditions = conditions;
    }
    
    public java.lang.String getFolder() {
        return folder;
    }
    
    public void setFolder(java.lang.String folder) {
        this.folder = folder;
    }
    
    public org.jboss.test.webservice.jbws718.BooleanOperatorEnum getBooleanOperator() {
        return booleanOperator;
    }
    
    public void setBooleanOperator(org.jboss.test.webservice.jbws718.BooleanOperatorEnum booleanOperator) {
        this.booleanOperator = booleanOperator;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfSearchCondition getConditions() {
        return conditions;
    }
    
    public void setConditions(org.jboss.test.webservice.jbws718.ArrayOfSearchCondition conditions) {
        this.conditions = conditions;
    }
}
