// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class FindItemsResponse {
    protected org.jboss.test.webservice.jbws718.ArrayOfCatalogItem items;
    
    public FindItemsResponse() {
    }
    
    public FindItemsResponse(org.jboss.test.webservice.jbws718.ArrayOfCatalogItem items) {
        this.items = items;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfCatalogItem getItems() {
        return items;
    }
    
    public void setItems(org.jboss.test.webservice.jbws718.ArrayOfCatalogItem items) {
        this.items = items;
    }
}
