// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class FireEvent {
    protected java.lang.String eventType;
    protected java.lang.String eventData;
    
    public FireEvent() {
    }
    
    public FireEvent(java.lang.String eventType, java.lang.String eventData) {
        this.eventType = eventType;
        this.eventData = eventData;
    }
    
    public java.lang.String getEventType() {
        return eventType;
    }
    
    public void setEventType(java.lang.String eventType) {
        this.eventType = eventType;
    }
    
    public java.lang.String getEventData() {
        return eventData;
    }
    
    public void setEventData(java.lang.String eventData) {
        this.eventData = eventData;
    }
}
