// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class GetDataSourceContentsResponse {
    protected org.jboss.test.webservice.jbws718.DataSourceDefinition definition;
    
    public GetDataSourceContentsResponse() {
    }
    
    public GetDataSourceContentsResponse(org.jboss.test.webservice.jbws718.DataSourceDefinition definition) {
        this.definition = definition;
    }
    
    public org.jboss.test.webservice.jbws718.DataSourceDefinition getDefinition() {
        return definition;
    }
    
    public void setDefinition(org.jboss.test.webservice.jbws718.DataSourceDefinition definition) {
        this.definition = definition;
    }
}
