// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class GetDataDrivenSubscriptionProperties {
    protected java.lang.String dataDrivenSubscriptionID;
    
    public GetDataDrivenSubscriptionProperties() {
    }
    
    public GetDataDrivenSubscriptionProperties(java.lang.String dataDrivenSubscriptionID) {
        this.dataDrivenSubscriptionID = dataDrivenSubscriptionID;
    }
    
    public java.lang.String getDataDrivenSubscriptionID() {
        return dataDrivenSubscriptionID;
    }
    
    public void setDataDrivenSubscriptionID(java.lang.String dataDrivenSubscriptionID) {
        this.dataDrivenSubscriptionID = dataDrivenSubscriptionID;
    }
}
