// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class GetExtensionSettingsResponse {
    protected org.jboss.test.webservice.jbws718.ArrayOfExtensionParameter extensionParameters;
    
    public GetExtensionSettingsResponse() {
    }
    
    public GetExtensionSettingsResponse(org.jboss.test.webservice.jbws718.ArrayOfExtensionParameter extensionParameters) {
        this.extensionParameters = extensionParameters;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfExtensionParameter getExtensionParameters() {
        return extensionParameters;
    }
    
    public void setExtensionParameters(org.jboss.test.webservice.jbws718.ArrayOfExtensionParameter extensionParameters) {
        this.extensionParameters = extensionParameters;
    }
}
