// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class GetExtensionSettings {
    protected java.lang.String extension;
    
    public GetExtensionSettings() {
    }
    
    public GetExtensionSettings(java.lang.String extension) {
        this.extension = extension;
    }
    
    public java.lang.String getExtension() {
        return extension;
    }
    
    public void setExtension(java.lang.String extension) {
        this.extension = extension;
    }
}
