// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class GetItemTypeResponse {
    protected org.jboss.test.webservice.jbws718.ItemTypeEnum type;
    
    public GetItemTypeResponse() {
    }
    
    public GetItemTypeResponse(org.jboss.test.webservice.jbws718.ItemTypeEnum type) {
        this.type = type;
    }
    
    public org.jboss.test.webservice.jbws718.ItemTypeEnum getType() {
        return type;
    }
    
    public void setType(org.jboss.test.webservice.jbws718.ItemTypeEnum type) {
        this.type = type;
    }
}
