// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class GetProperties {
    protected java.lang.String item;
    protected org.jboss.test.webservice.jbws718.ArrayOfProperty properties;
    
    public GetProperties() {
    }
    
    public GetProperties(java.lang.String item, org.jboss.test.webservice.jbws718.ArrayOfProperty properties) {
        this.item = item;
        this.properties = properties;
    }
    
    public java.lang.String getItem() {
        return item;
    }
    
    public void setItem(java.lang.String item) {
        this.item = item;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfProperty getProperties() {
        return properties;
    }
    
    public void setProperties(org.jboss.test.webservice.jbws718.ArrayOfProperty properties) {
        this.properties = properties;
    }
}
