// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class GetPermissionsResponse {
    protected org.jboss.test.webservice.jbws718.ArrayOfString3 permissions;
    
    public GetPermissionsResponse() {
    }
    
    public GetPermissionsResponse(org.jboss.test.webservice.jbws718.ArrayOfString3 permissions) {
        this.permissions = permissions;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfString3 getPermissions() {
        return permissions;
    }
    
    public void setPermissions(org.jboss.test.webservice.jbws718.ArrayOfString3 permissions) {
        this.permissions = permissions;
    }
}
