// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class GetReportParametersResponse {
    protected org.jboss.test.webservice.jbws718.ArrayOfReportParameter parameters;
    
    public GetReportParametersResponse() {
    }
    
    public GetReportParametersResponse(org.jboss.test.webservice.jbws718.ArrayOfReportParameter parameters) {
        this.parameters = parameters;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfReportParameter getParameters() {
        return parameters;
    }
    
    public void setParameters(org.jboss.test.webservice.jbws718.ArrayOfReportParameter parameters) {
        this.parameters = parameters;
    }
}
