// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class GetReportDefinitionResponse {
    protected byte[] definition;
    
    public GetReportDefinitionResponse() {
    }
    
    public GetReportDefinitionResponse(byte[] definition) {
        this.definition = definition;
    }
    
    public byte[] getDefinition() {
        return definition;
    }
    
    public void setDefinition(byte[] definition) {
        this.definition = definition;
    }
}
