// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class GetReportParameters {
    protected java.lang.String report;
    protected java.lang.String historyID;
    protected boolean forRendering;
    protected org.jboss.test.webservice.jbws718.ArrayOfParameterValue values;
    protected org.jboss.test.webservice.jbws718.ArrayOfDataSourceCredentials credentials;
    
    public GetReportParameters() {
    }
    
    public GetReportParameters(java.lang.String report, java.lang.String historyID, boolean forRendering, org.jboss.test.webservice.jbws718.ArrayOfParameterValue values, org.jboss.test.webservice.jbws718.ArrayOfDataSourceCredentials credentials) {
        this.report = report;
        this.historyID = historyID;
        this.forRendering = forRendering;
        this.values = values;
        this.credentials = credentials;
    }
    
    public java.lang.String getReport() {
        return report;
    }
    
    public void setReport(java.lang.String report) {
        this.report = report;
    }
    
    public java.lang.String getHistoryID() {
        return historyID;
    }
    
    public void setHistoryID(java.lang.String historyID) {
        this.historyID = historyID;
    }
    
    public boolean isForRendering() {
        return forRendering;
    }
    
    public void setForRendering(boolean forRendering) {
        this.forRendering = forRendering;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfParameterValue getValues() {
        return values;
    }
    
    public void setValues(org.jboss.test.webservice.jbws718.ArrayOfParameterValue values) {
        this.values = values;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfDataSourceCredentials getCredentials() {
        return credentials;
    }
    
    public void setCredentials(org.jboss.test.webservice.jbws718.ArrayOfDataSourceCredentials credentials) {
        this.credentials = credentials;
    }
}
