// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class GetReportDataSourcesResponse {
    protected org.jboss.test.webservice.jbws718.ArrayOfDataSource dataSources;
    
    public GetReportDataSourcesResponse() {
    }
    
    public GetReportDataSourcesResponse(org.jboss.test.webservice.jbws718.ArrayOfDataSource dataSources) {
        this.dataSources = dataSources;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfDataSource getDataSources() {
        return dataSources;
    }
    
    public void setDataSources(org.jboss.test.webservice.jbws718.ArrayOfDataSource dataSources) {
        this.dataSources = dataSources;
    }
}
