// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class GetRenderResource {
    protected java.lang.String format;
    protected java.lang.String deviceInfo;
    
    public GetRenderResource() {
    }
    
    public GetRenderResource(java.lang.String format, java.lang.String deviceInfo) {
        this.format = format;
        this.deviceInfo = deviceInfo;
    }
    
    public java.lang.String getFormat() {
        return format;
    }
    
    public void setFormat(java.lang.String format) {
        this.format = format;
    }
    
    public java.lang.String getDeviceInfo() {
        return deviceInfo;
    }
    
    public void setDeviceInfo(java.lang.String deviceInfo) {
        this.deviceInfo = deviceInfo;
    }
}
