// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class GetRenderResourceResponse {
    protected byte[] result;
    protected java.lang.String mimeType;
    
    public GetRenderResourceResponse() {
    }
    
    public GetRenderResourceResponse(byte[] result, java.lang.String mimeType) {
        this.result = result;
        this.mimeType = mimeType;
    }
    
    public byte[] getResult() {
        return result;
    }
    
    public void setResult(byte[] result) {
        this.result = result;
    }
    
    public java.lang.String getMimeType() {
        return mimeType;
    }
    
    public void setMimeType(java.lang.String mimeType) {
        this.mimeType = mimeType;
    }
}
