// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class GetResourceContents {
    protected java.lang.String resource;
    
    public GetResourceContents() {
    }
    
    public GetResourceContents(java.lang.String resource) {
        this.resource = resource;
    }
    
    public java.lang.String getResource() {
        return resource;
    }
    
    public void setResource(java.lang.String resource) {
        this.resource = resource;
    }
}
