// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class GetReportLinkResponse {
    protected java.lang.String link;
    
    public GetReportLinkResponse() {
    }
    
    public GetReportLinkResponse(java.lang.String link) {
        this.link = link;
    }
    
    public java.lang.String getLink() {
        return link;
    }
    
    public void setLink(java.lang.String link) {
        this.link = link;
    }
}
