// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class GetReportDataSourcePromptsResponse {
    protected org.jboss.test.webservice.jbws718.ArrayOfDataSourcePrompt dataSourcePrompts;
    
    public GetReportDataSourcePromptsResponse() {
    }
    
    public GetReportDataSourcePromptsResponse(org.jboss.test.webservice.jbws718.ArrayOfDataSourcePrompt dataSourcePrompts) {
        this.dataSourcePrompts = dataSourcePrompts;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfDataSourcePrompt getDataSourcePrompts() {
        return dataSourcePrompts;
    }
    
    public void setDataSourcePrompts(org.jboss.test.webservice.jbws718.ArrayOfDataSourcePrompt dataSourcePrompts) {
        this.dataSourcePrompts = dataSourcePrompts;
    }
}
