// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class GetSystemProperties {
    protected org.jboss.test.webservice.jbws718.ArrayOfProperty properties;
    
    public GetSystemProperties() {
    }
    
    public GetSystemProperties(org.jboss.test.webservice.jbws718.ArrayOfProperty properties) {
        this.properties = properties;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfProperty getProperties() {
        return properties;
    }
    
    public void setProperties(org.jboss.test.webservice.jbws718.ArrayOfProperty properties) {
        this.properties = properties;
    }
}
