// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class GetSystemPropertiesResponse {
    protected org.jboss.test.webservice.jbws718.ArrayOfProperty values;
    
    public GetSystemPropertiesResponse() {
    }
    
    public GetSystemPropertiesResponse(org.jboss.test.webservice.jbws718.ArrayOfProperty values) {
        this.values = values;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfProperty getValues() {
        return values;
    }
    
    public void setValues(org.jboss.test.webservice.jbws718.ArrayOfProperty values) {
        this.values = values;
    }
}
