// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


import java.util.Map;
import java.util.HashMap;

public class ItemTypeEnum {
    private java.lang.String value;
    private static java.util.Map valueMap = new HashMap();
    public static final java.lang.String _UnknownString = "Unknown";
    public static final java.lang.String _FolderString = "Folder";
    public static final java.lang.String _ReportString = "Report";
    public static final java.lang.String _ResourceString = "Resource";
    public static final java.lang.String _LinkedReportString = "LinkedReport";
    public static final java.lang.String _DataSourceString = "DataSource";
    
    public static final java.lang.String _Unknown = new java.lang.String(_UnknownString);
    public static final java.lang.String _Folder = new java.lang.String(_FolderString);
    public static final java.lang.String _Report = new java.lang.String(_ReportString);
    public static final java.lang.String _Resource = new java.lang.String(_ResourceString);
    public static final java.lang.String _LinkedReport = new java.lang.String(_LinkedReportString);
    public static final java.lang.String _DataSource = new java.lang.String(_DataSourceString);
    
    public static final ItemTypeEnum Unknown = new ItemTypeEnum(_Unknown);
    public static final ItemTypeEnum Folder = new ItemTypeEnum(_Folder);
    public static final ItemTypeEnum Report = new ItemTypeEnum(_Report);
    public static final ItemTypeEnum Resource = new ItemTypeEnum(_Resource);
    public static final ItemTypeEnum LinkedReport = new ItemTypeEnum(_LinkedReport);
    public static final ItemTypeEnum DataSource = new ItemTypeEnum(_DataSource);
    
    protected ItemTypeEnum(java.lang.String value) {
        this.value = value;
        valueMap.put(this.toString(), this);
    }
    
    public java.lang.String getValue() {
        return value;
    }
    
    public static ItemTypeEnum fromValue(java.lang.String value)
        throws java.lang.IllegalStateException {
        if (Unknown.value.equals(value)) {
            return Unknown;
        } else if (Folder.value.equals(value)) {
            return Folder;
        } else if (Report.value.equals(value)) {
            return Report;
        } else if (Resource.value.equals(value)) {
            return Resource;
        } else if (LinkedReport.value.equals(value)) {
            return LinkedReport;
        } else if (DataSource.value.equals(value)) {
            return DataSource;
        }
        throw new java.lang.IllegalArgumentException();
    }
    
    public static ItemTypeEnum fromString(java.lang.String value)
        throws java.lang.IllegalStateException {
        ItemTypeEnum ret = (ItemTypeEnum)valueMap.get(value);
        if (ret != null) {
            return ret;
        }
        if (value.equals(_UnknownString)) {
            return Unknown;
        } else if (value.equals(_FolderString)) {
            return Folder;
        } else if (value.equals(_ReportString)) {
            return Report;
        } else if (value.equals(_ResourceString)) {
            return Resource;
        } else if (value.equals(_LinkedReportString)) {
            return LinkedReport;
        } else if (value.equals(_DataSourceString)) {
            return DataSource;
        }
        throw new IllegalArgumentException();
    }
    
    public java.lang.String toString() {
        return value.toString();
    }
    
    private java.lang.Object readResolve()
        throws java.io.ObjectStreamException {
        return fromValue(getValue());
    }
    
    public boolean equals(java.lang.Object obj) {
        if (!(obj instanceof ItemTypeEnum)) {
            return false;
        }
        return ((ItemTypeEnum)obj).value.equals(value);
    }
    
    public int hashCode() {
        return value.hashCode();
    }
}
