// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class Job {
    protected java.lang.String jobID;
    protected java.lang.String name;
    protected java.lang.String path;
    protected java.lang.String description;
    protected java.lang.String machine;
    protected java.lang.String user;
    protected java.util.Calendar startDateTime;
    protected org.jboss.test.webservice.jbws718.JobActionEnum action;
    protected org.jboss.test.webservice.jbws718.JobTypeEnum type;
    protected org.jboss.test.webservice.jbws718.JobStatusEnum status;
    
    public Job() {
    }
    
    public Job(java.lang.String jobID, java.lang.String name, java.lang.String path, java.lang.String description, java.lang.String machine, java.lang.String user, java.util.Calendar startDateTime, org.jboss.test.webservice.jbws718.JobActionEnum action, org.jboss.test.webservice.jbws718.JobTypeEnum type, org.jboss.test.webservice.jbws718.JobStatusEnum status) {
        this.jobID = jobID;
        this.name = name;
        this.path = path;
        this.description = description;
        this.machine = machine;
        this.user = user;
        this.startDateTime = startDateTime;
        this.action = action;
        this.type = type;
        this.status = status;
    }
    
    public java.lang.String getJobID() {
        return jobID;
    }
    
    public void setJobID(java.lang.String jobID) {
        this.jobID = jobID;
    }
    
    public java.lang.String getName() {
        return name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public java.lang.String getPath() {
        return path;
    }
    
    public void setPath(java.lang.String path) {
        this.path = path;
    }
    
    public java.lang.String getDescription() {
        return description;
    }
    
    public void setDescription(java.lang.String description) {
        this.description = description;
    }
    
    public java.lang.String getMachine() {
        return machine;
    }
    
    public void setMachine(java.lang.String machine) {
        this.machine = machine;
    }
    
    public java.lang.String getUser() {
        return user;
    }
    
    public void setUser(java.lang.String user) {
        this.user = user;
    }
    
    public java.util.Calendar getStartDateTime() {
        return startDateTime;
    }
    
    public void setStartDateTime(java.util.Calendar startDateTime) {
        this.startDateTime = startDateTime;
    }
    
    public org.jboss.test.webservice.jbws718.JobActionEnum getAction() {
        return action;
    }
    
    public void setAction(org.jboss.test.webservice.jbws718.JobActionEnum action) {
        this.action = action;
    }
    
    public org.jboss.test.webservice.jbws718.JobTypeEnum getType() {
        return type;
    }
    
    public void setType(org.jboss.test.webservice.jbws718.JobTypeEnum type) {
        this.type = type;
    }
    
    public org.jboss.test.webservice.jbws718.JobStatusEnum getStatus() {
        return status;
    }
    
    public void setStatus(org.jboss.test.webservice.jbws718.JobStatusEnum status) {
        this.status = status;
    }
}
