// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


import java.util.Map;
import java.util.HashMap;

public class JobActionEnum {
    private java.lang.String value;
    private static java.util.Map valueMap = new HashMap();
    public static final java.lang.String _RenderString = "Render";
    public static final java.lang.String _SnapshotCreationString = "SnapshotCreation";
    public static final java.lang.String _ReportHistoryCreationString = "ReportHistoryCreation";
    
    public static final java.lang.String _Render = new java.lang.String(_RenderString);
    public static final java.lang.String _SnapshotCreation = new java.lang.String(_SnapshotCreationString);
    public static final java.lang.String _ReportHistoryCreation = new java.lang.String(_ReportHistoryCreationString);
    
    public static final JobActionEnum Render = new JobActionEnum(_Render);
    public static final JobActionEnum SnapshotCreation = new JobActionEnum(_SnapshotCreation);
    public static final JobActionEnum ReportHistoryCreation = new JobActionEnum(_ReportHistoryCreation);
    
    protected JobActionEnum(java.lang.String value) {
        this.value = value;
        valueMap.put(this.toString(), this);
    }
    
    public java.lang.String getValue() {
        return value;
    }
    
    public static JobActionEnum fromValue(java.lang.String value)
        throws java.lang.IllegalStateException {
        if (Render.value.equals(value)) {
            return Render;
        } else if (SnapshotCreation.value.equals(value)) {
            return SnapshotCreation;
        } else if (ReportHistoryCreation.value.equals(value)) {
            return ReportHistoryCreation;
        }
        throw new java.lang.IllegalArgumentException();
    }
    
    public static JobActionEnum fromString(java.lang.String value)
        throws java.lang.IllegalStateException {
        JobActionEnum ret = (JobActionEnum)valueMap.get(value);
        if (ret != null) {
            return ret;
        }
        if (value.equals(_RenderString)) {
            return Render;
        } else if (value.equals(_SnapshotCreationString)) {
            return SnapshotCreation;
        } else if (value.equals(_ReportHistoryCreationString)) {
            return ReportHistoryCreation;
        }
        throw new IllegalArgumentException();
    }
    
    public java.lang.String toString() {
        return value.toString();
    }
    
    private java.lang.Object readResolve()
        throws java.io.ObjectStreamException {
        return fromValue(getValue());
    }
    
    public boolean equals(java.lang.Object obj) {
        if (!(obj instanceof JobActionEnum)) {
            return false;
        }
        return ((JobActionEnum)obj).value.equals(value);
    }
    
    public int hashCode() {
        return value.hashCode();
    }
}
