// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ListSubscriptionsUsingDataSourceResponse {
    protected org.jboss.test.webservice.jbws718.ArrayOfSubscription subscriptionItems;
    
    public ListSubscriptionsUsingDataSourceResponse() {
    }
    
    public ListSubscriptionsUsingDataSourceResponse(org.jboss.test.webservice.jbws718.ArrayOfSubscription subscriptionItems) {
        this.subscriptionItems = subscriptionItems;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfSubscription getSubscriptionItems() {
        return subscriptionItems;
    }
    
    public void setSubscriptionItems(org.jboss.test.webservice.jbws718.ArrayOfSubscription subscriptionItems) {
        this.subscriptionItems = subscriptionItems;
    }
}
