// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ListScheduledReportsResponse {
    protected org.jboss.test.webservice.jbws718.ArrayOfCatalogItem reports;
    
    public ListScheduledReportsResponse() {
    }
    
    public ListScheduledReportsResponse(org.jboss.test.webservice.jbws718.ArrayOfCatalogItem reports) {
        this.reports = reports;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfCatalogItem getReports() {
        return reports;
    }
    
    public void setReports(org.jboss.test.webservice.jbws718.ArrayOfCatalogItem reports) {
        this.reports = reports;
    }
}
