// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ListExtensions {
    protected org.jboss.test.webservice.jbws718.ExtensionTypeEnum extensionType;
    
    public ListExtensions() {
    }
    
    public ListExtensions(org.jboss.test.webservice.jbws718.ExtensionTypeEnum extensionType) {
        this.extensionType = extensionType;
    }
    
    public org.jboss.test.webservice.jbws718.ExtensionTypeEnum getExtensionType() {
        return extensionType;
    }
    
    public void setExtensionType(org.jboss.test.webservice.jbws718.ExtensionTypeEnum extensionType) {
        this.extensionType = extensionType;
    }
}
