// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ListSystemRolesResponse {
    protected org.jboss.test.webservice.jbws718.ArrayOfRole roles;
    
    public ListSystemRolesResponse() {
    }
    
    public ListSystemRolesResponse(org.jboss.test.webservice.jbws718.ArrayOfRole roles) {
        this.roles = roles;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfRole getRoles() {
        return roles;
    }
    
    public void setRoles(org.jboss.test.webservice.jbws718.ArrayOfRole roles) {
        this.roles = roles;
    }
}
