// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ListSecureMethodsResponse {
    protected org.jboss.test.webservice.jbws718.ArrayOfString listSecureMethodsResult;
    
    public ListSecureMethodsResponse() {
    }
    
    public ListSecureMethodsResponse(org.jboss.test.webservice.jbws718.ArrayOfString listSecureMethodsResult) {
        this.listSecureMethodsResult = listSecureMethodsResult;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfString getListSecureMethodsResult() {
        return listSecureMethodsResult;
    }
    
    public void setListSecureMethodsResult(org.jboss.test.webservice.jbws718.ArrayOfString listSecureMethodsResult) {
        this.listSecureMethodsResult = listSecureMethodsResult;
    }
}
