// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ListExtensionsResponse {
    protected org.jboss.test.webservice.jbws718.ArrayOfExtension extensions;
    
    public ListExtensionsResponse() {
    }
    
    public ListExtensionsResponse(org.jboss.test.webservice.jbws718.ArrayOfExtension extensions) {
        this.extensions = extensions;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfExtension getExtensions() {
        return extensions;
    }
    
    public void setExtensions(org.jboss.test.webservice.jbws718.ArrayOfExtension extensions) {
        this.extensions = extensions;
    }
}
