// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ListEventsResponse {
    protected org.jboss.test.webservice.jbws718.ArrayOfEvent events;
    
    public ListEventsResponse() {
    }
    
    public ListEventsResponse(org.jboss.test.webservice.jbws718.ArrayOfEvent events) {
        this.events = events;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfEvent getEvents() {
        return events;
    }
    
    public void setEvents(org.jboss.test.webservice.jbws718.ArrayOfEvent events) {
        this.events = events;
    }
}
