// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ListSubscriptions {
    protected java.lang.String report;
    protected java.lang.String owner;
    
    public ListSubscriptions() {
    }
    
    public ListSubscriptions(java.lang.String report, java.lang.String owner) {
        this.report = report;
        this.owner = owner;
    }
    
    public java.lang.String getReport() {
        return report;
    }
    
    public void setReport(java.lang.String report) {
        this.report = report;
    }
    
    public java.lang.String getOwner() {
        return owner;
    }
    
    public void setOwner(java.lang.String owner) {
        this.owner = owner;
    }
}
