// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ListTasksResponse {
    protected org.jboss.test.webservice.jbws718.ArrayOfTask tasks;
    
    public ListTasksResponse() {
    }
    
    public ListTasksResponse(org.jboss.test.webservice.jbws718.ArrayOfTask tasks) {
        this.tasks = tasks;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfTask getTasks() {
        return tasks;
    }
    
    public void setTasks(org.jboss.test.webservice.jbws718.ArrayOfTask tasks) {
        this.tasks = tasks;
    }
}
