// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ListJobsResponse {
    protected org.jboss.test.webservice.jbws718.ArrayOfJob jobs;
    
    public ListJobsResponse() {
    }
    
    public ListJobsResponse(org.jboss.test.webservice.jbws718.ArrayOfJob jobs) {
        this.jobs = jobs;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfJob getJobs() {
        return jobs;
    }
    
    public void setJobs(org.jboss.test.webservice.jbws718.ArrayOfJob jobs) {
        this.jobs = jobs;
    }
}
