// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ListSchedulesResponse {
    protected org.jboss.test.webservice.jbws718.ArrayOfSchedule schedules;
    
    public ListSchedulesResponse() {
    }
    
    public ListSchedulesResponse(org.jboss.test.webservice.jbws718.ArrayOfSchedule schedules) {
        this.schedules = schedules;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfSchedule getSchedules() {
        return schedules;
    }
    
    public void setSchedules(org.jboss.test.webservice.jbws718.ArrayOfSchedule schedules) {
        this.schedules = schedules;
    }
}
