// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ListChildrenResponse {
    protected org.jboss.test.webservice.jbws718.ArrayOfCatalogItem catalogItems;
    
    public ListChildrenResponse() {
    }
    
    public ListChildrenResponse(org.jboss.test.webservice.jbws718.ArrayOfCatalogItem catalogItems) {
        this.catalogItems = catalogItems;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfCatalogItem getCatalogItems() {
        return catalogItems;
    }
    
    public void setCatalogItems(org.jboss.test.webservice.jbws718.ArrayOfCatalogItem catalogItems) {
        this.catalogItems = catalogItems;
    }
}
