// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ListReportHistoryResponse {
    protected org.jboss.test.webservice.jbws718.ArrayOfReportHistorySnapshot reportHistory;
    
    public ListReportHistoryResponse() {
    }
    
    public ListReportHistoryResponse(org.jboss.test.webservice.jbws718.ArrayOfReportHistorySnapshot reportHistory) {
        this.reportHistory = reportHistory;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfReportHistorySnapshot getReportHistory() {
        return reportHistory;
    }
    
    public void setReportHistory(org.jboss.test.webservice.jbws718.ArrayOfReportHistorySnapshot reportHistory) {
        this.reportHistory = reportHistory;
    }
}
