// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ListChildren {
    protected java.lang.String item;
    protected boolean recursive;
    
    public ListChildren() {
    }
    
    public ListChildren(java.lang.String item, boolean recursive) {
        this.item = item;
        this.recursive = recursive;
    }
    
    public java.lang.String getItem() {
        return item;
    }
    
    public void setItem(java.lang.String item) {
        this.item = item;
    }
    
    public boolean isRecursive() {
        return recursive;
    }
    
    public void setRecursive(boolean recursive) {
        this.recursive = recursive;
    }
}
