// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class MoveItem {
    protected java.lang.String item;
    protected java.lang.String target;
    
    public MoveItem() {
    }
    
    public MoveItem(java.lang.String item, java.lang.String target) {
        this.item = item;
        this.target = target;
    }
    
    public java.lang.String getItem() {
        return item;
    }
    
    public void setItem(java.lang.String item) {
        this.item = item;
    }
    
    public java.lang.String getTarget() {
        return target;
    }
    
    public void setTarget(java.lang.String target) {
        this.target = target;
    }
}
