// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ParameterValue extends org.jboss.test.webservice.jbws718.ParameterValueOrFieldReference {
    protected java.lang.String name;
    protected java.lang.String value;
    protected java.lang.String label;
    
    public ParameterValue() {
    }
    
    public ParameterValue(java.lang.String name, java.lang.String value, java.lang.String label) {
        this.name = name;
        this.value = value;
        this.label = label;
    }
    
    public java.lang.String getName() {
        return name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public java.lang.String getValue() {
        return value;
    }
    
    public void setValue(java.lang.String value) {
        this.value = value;
    }
    
    public java.lang.String getLabel() {
        return label;
    }
    
    public void setLabel(java.lang.String label) {
        this.label = label;
    }
}
