// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class Policy {
    protected java.lang.String groupUserName;
    protected org.jboss.test.webservice.jbws718.ArrayOfRole roles;
    
    public Policy() {
    }
    
    public Policy(java.lang.String groupUserName, org.jboss.test.webservice.jbws718.ArrayOfRole roles) {
        this.groupUserName = groupUserName;
        this.roles = roles;
    }
    
    public java.lang.String getGroupUserName() {
        return groupUserName;
    }
    
    public void setGroupUserName(java.lang.String groupUserName) {
        this.groupUserName = groupUserName;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfRole getRoles() {
        return roles;
    }
    
    public void setRoles(org.jboss.test.webservice.jbws718.ArrayOfRole roles) {
        this.roles = roles;
    }
}
