// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class PrepareQuery {
    protected javax.xml.soap.SOAPElement dataSource;
    protected org.jboss.test.webservice.jbws718.DataSetDefinition dataSet;
    
    public PrepareQuery() {
    }
    
    public PrepareQuery(javax.xml.soap.SOAPElement dataSource, org.jboss.test.webservice.jbws718.DataSetDefinition dataSet) {
        this.dataSource = dataSource;
        this.dataSet = dataSet;
    }
    
    public javax.xml.soap.SOAPElement getDataSource() {
        return dataSource;
    }
    
    public void setDataSource(javax.xml.soap.SOAPElement dataSource) {
        this.dataSource = dataSource;
    }
    
    public org.jboss.test.webservice.jbws718.DataSetDefinition getDataSet() {
        return dataSet;
    }
    
    public void setDataSet(org.jboss.test.webservice.jbws718.DataSetDefinition dataSet) {
        this.dataSet = dataSet;
    }
}
