// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class PrepareQueryResponse {
    protected org.jboss.test.webservice.jbws718.DataSetDefinition dataSettings;
    protected boolean changed;
    
    public PrepareQueryResponse() {
    }
    
    public PrepareQueryResponse(org.jboss.test.webservice.jbws718.DataSetDefinition dataSettings, boolean changed) {
        this.dataSettings = dataSettings;
        this.changed = changed;
    }
    
    public org.jboss.test.webservice.jbws718.DataSetDefinition getDataSettings() {
        return dataSettings;
    }
    
    public void setDataSettings(org.jboss.test.webservice.jbws718.DataSetDefinition dataSettings) {
        this.dataSettings = dataSettings;
    }
    
    public boolean isChanged() {
        return changed;
    }
    
    public void setChanged(boolean changed) {
        this.changed = changed;
    }
}
