// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class QueryDefinition {
    protected java.lang.String commandType;
    protected java.lang.String commandText;
    protected java.lang.Integer timeout;
    
    public QueryDefinition() {
    }
    
    public QueryDefinition(java.lang.String commandType, java.lang.String commandText, java.lang.Integer timeout) {
        this.commandType = commandType;
        this.commandText = commandText;
        this.timeout = timeout;
    }
    
    public java.lang.String getCommandType() {
        return commandType;
    }
    
    public void setCommandType(java.lang.String commandType) {
        this.commandType = commandType;
    }
    
    public java.lang.String getCommandText() {
        return commandText;
    }
    
    public void setCommandText(java.lang.String commandText) {
        this.commandText = commandText;
    }
    
    public java.lang.Integer getTimeout() {
        return timeout;
    }
    
    public void setTimeout(java.lang.Integer timeout) {
        this.timeout = timeout;
    }
}
