// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class RenderStream {
    protected java.lang.String report;
    protected java.lang.String format;
    protected java.lang.String streamID;
    protected java.lang.String historyID;
    protected java.lang.String deviceInfo;
    protected org.jboss.test.webservice.jbws718.ArrayOfParameterValue parameters;
    
    public RenderStream() {
    }
    
    public RenderStream(java.lang.String report, java.lang.String format, java.lang.String streamID, java.lang.String historyID, java.lang.String deviceInfo, org.jboss.test.webservice.jbws718.ArrayOfParameterValue parameters) {
        this.report = report;
        this.format = format;
        this.streamID = streamID;
        this.historyID = historyID;
        this.deviceInfo = deviceInfo;
        this.parameters = parameters;
    }
    
    public java.lang.String getReport() {
        return report;
    }
    
    public void setReport(java.lang.String report) {
        this.report = report;
    }
    
    public java.lang.String getFormat() {
        return format;
    }
    
    public void setFormat(java.lang.String format) {
        this.format = format;
    }
    
    public java.lang.String getStreamID() {
        return streamID;
    }
    
    public void setStreamID(java.lang.String streamID) {
        this.streamID = streamID;
    }
    
    public java.lang.String getHistoryID() {
        return historyID;
    }
    
    public void setHistoryID(java.lang.String historyID) {
        this.historyID = historyID;
    }
    
    public java.lang.String getDeviceInfo() {
        return deviceInfo;
    }
    
    public void setDeviceInfo(java.lang.String deviceInfo) {
        this.deviceInfo = deviceInfo;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfParameterValue getParameters() {
        return parameters;
    }
    
    public void setParameters(org.jboss.test.webservice.jbws718.ArrayOfParameterValue parameters) {
        this.parameters = parameters;
    }
}
