// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class RenderStreamResponse {
    protected byte[] result;
    protected java.lang.String encoding;
    protected java.lang.String mimeType;
    
    public RenderStreamResponse() {
    }
    
    public RenderStreamResponse(byte[] result, java.lang.String encoding, java.lang.String mimeType) {
        this.result = result;
        this.encoding = encoding;
        this.mimeType = mimeType;
    }
    
    public byte[] getResult() {
        return result;
    }
    
    public void setResult(byte[] result) {
        this.result = result;
    }
    
    public java.lang.String getEncoding() {
        return encoding;
    }
    
    public void setEncoding(java.lang.String encoding) {
        this.encoding = encoding;
    }
    
    public java.lang.String getMimeType() {
        return mimeType;
    }
    
    public void setMimeType(java.lang.String mimeType) {
        this.mimeType = mimeType;
    }
}
