// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ReportParameter {
    protected java.lang.String name;
    protected org.jboss.test.webservice.jbws718.ParameterTypeEnum type;
    protected java.lang.Boolean nullable;
    protected java.lang.Boolean allowBlank;
    protected java.lang.Boolean multiValue;
    protected java.lang.Boolean queryParameter;
    protected java.lang.String prompt;
    protected java.lang.Boolean promptUser;
    protected org.jboss.test.webservice.jbws718.ArrayOfString1 dependencies;
    protected java.lang.Boolean validValuesQueryBased;
    protected org.jboss.test.webservice.jbws718.ArrayOfValidValue validValues;
    protected java.lang.Boolean defaultValuesQueryBased;
    protected org.jboss.test.webservice.jbws718.ArrayOfString2 defaultValues;
    protected org.jboss.test.webservice.jbws718.ParameterStateEnum state;
    protected java.lang.String errorMessage;
    
    public ReportParameter() {
    }
    
    public ReportParameter(java.lang.String name, org.jboss.test.webservice.jbws718.ParameterTypeEnum type, java.lang.Boolean nullable, java.lang.Boolean allowBlank, java.lang.Boolean multiValue, java.lang.Boolean queryParameter, java.lang.String prompt, java.lang.Boolean promptUser, org.jboss.test.webservice.jbws718.ArrayOfString1 dependencies, java.lang.Boolean validValuesQueryBased, org.jboss.test.webservice.jbws718.ArrayOfValidValue validValues, java.lang.Boolean defaultValuesQueryBased, org.jboss.test.webservice.jbws718.ArrayOfString2 defaultValues, org.jboss.test.webservice.jbws718.ParameterStateEnum state, java.lang.String errorMessage) {
        this.name = name;
        this.type = type;
        this.nullable = nullable;
        this.allowBlank = allowBlank;
        this.multiValue = multiValue;
        this.queryParameter = queryParameter;
        this.prompt = prompt;
        this.promptUser = promptUser;
        this.dependencies = dependencies;
        this.validValuesQueryBased = validValuesQueryBased;
        this.validValues = validValues;
        this.defaultValuesQueryBased = defaultValuesQueryBased;
        this.defaultValues = defaultValues;
        this.state = state;
        this.errorMessage = errorMessage;
    }
    
    public java.lang.String getName() {
        return name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public org.jboss.test.webservice.jbws718.ParameterTypeEnum getType() {
        return type;
    }
    
    public void setType(org.jboss.test.webservice.jbws718.ParameterTypeEnum type) {
        this.type = type;
    }
    
    public java.lang.Boolean getNullable() {
        return nullable;
    }
    
    public void setNullable(java.lang.Boolean nullable) {
        this.nullable = nullable;
    }
    
    public java.lang.Boolean getAllowBlank() {
        return allowBlank;
    }
    
    public void setAllowBlank(java.lang.Boolean allowBlank) {
        this.allowBlank = allowBlank;
    }
    
    public java.lang.Boolean getMultiValue() {
        return multiValue;
    }
    
    public void setMultiValue(java.lang.Boolean multiValue) {
        this.multiValue = multiValue;
    }
    
    public java.lang.Boolean getQueryParameter() {
        return queryParameter;
    }
    
    public void setQueryParameter(java.lang.Boolean queryParameter) {
        this.queryParameter = queryParameter;
    }
    
    public java.lang.String getPrompt() {
        return prompt;
    }
    
    public void setPrompt(java.lang.String prompt) {
        this.prompt = prompt;
    }
    
    public java.lang.Boolean getPromptUser() {
        return promptUser;
    }
    
    public void setPromptUser(java.lang.Boolean promptUser) {
        this.promptUser = promptUser;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfString1 getDependencies() {
        return dependencies;
    }
    
    public void setDependencies(org.jboss.test.webservice.jbws718.ArrayOfString1 dependencies) {
        this.dependencies = dependencies;
    }
    
    public java.lang.Boolean getValidValuesQueryBased() {
        return validValuesQueryBased;
    }
    
    public void setValidValuesQueryBased(java.lang.Boolean validValuesQueryBased) {
        this.validValuesQueryBased = validValuesQueryBased;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfValidValue getValidValues() {
        return validValues;
    }
    
    public void setValidValues(org.jboss.test.webservice.jbws718.ArrayOfValidValue validValues) {
        this.validValues = validValues;
    }
    
    public java.lang.Boolean getDefaultValuesQueryBased() {
        return defaultValuesQueryBased;
    }
    
    public void setDefaultValuesQueryBased(java.lang.Boolean defaultValuesQueryBased) {
        this.defaultValuesQueryBased = defaultValuesQueryBased;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfString2 getDefaultValues() {
        return defaultValues;
    }
    
    public void setDefaultValues(org.jboss.test.webservice.jbws718.ArrayOfString2 defaultValues) {
        this.defaultValues = defaultValues;
    }
    
    public org.jboss.test.webservice.jbws718.ParameterStateEnum getState() {
        return state;
    }
    
    public void setState(org.jboss.test.webservice.jbws718.ParameterStateEnum state) {
        this.state = state;
    }
    
    public java.lang.String getErrorMessage() {
        return errorMessage;
    }
    
    public void setErrorMessage(java.lang.String errorMessage) {
        this.errorMessage = errorMessage;
    }
}
