// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ResumeSchedule {
    protected java.lang.String scheduleID;
    
    public ResumeSchedule() {
    }
    
    public ResumeSchedule(java.lang.String scheduleID) {
        this.scheduleID = scheduleID;
    }
    
    public java.lang.String getScheduleID() {
        return scheduleID;
    }
    
    public void setScheduleID(java.lang.String scheduleID) {
        this.scheduleID = scheduleID;
    }
}
