// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class SearchCondition extends org.jboss.test.webservice.jbws718.Property {
    protected org.jboss.test.webservice.jbws718.ConditionEnum condition;
    
    public SearchCondition() {
    }
    
    public SearchCondition(java.lang.String name, java.lang.String value, org.jboss.test.webservice.jbws718.ConditionEnum condition) {
        this.name = name;
        this.value = value;
        this.condition = condition;
    }
    
    public org.jboss.test.webservice.jbws718.ConditionEnum getCondition() {
        return condition;
    }
    
    public void setCondition(org.jboss.test.webservice.jbws718.ConditionEnum condition) {
        this.condition = condition;
    }
}
