// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class SetDataDrivenSubscriptionProperties {
    protected java.lang.String dataDrivenSubscriptionID;
    protected org.jboss.test.webservice.jbws718.ExtensionSettings extensionSettings;
    protected javax.xml.soap.SOAPElement dataRetrievalPlan;
    protected java.lang.String description;
    protected java.lang.String eventType;
    protected java.lang.String matchData;
    protected org.jboss.test.webservice.jbws718.ArrayOfParameterValueOrFieldReference parameters;
    
    public SetDataDrivenSubscriptionProperties() {
    }
    
    public SetDataDrivenSubscriptionProperties(java.lang.String dataDrivenSubscriptionID, org.jboss.test.webservice.jbws718.ExtensionSettings extensionSettings, javax.xml.soap.SOAPElement dataRetrievalPlan, java.lang.String description, java.lang.String eventType, java.lang.String matchData, org.jboss.test.webservice.jbws718.ArrayOfParameterValueOrFieldReference parameters) {
        this.dataDrivenSubscriptionID = dataDrivenSubscriptionID;
        this.extensionSettings = extensionSettings;
        this.dataRetrievalPlan = dataRetrievalPlan;
        this.description = description;
        this.eventType = eventType;
        this.matchData = matchData;
        this.parameters = parameters;
    }
    
    public java.lang.String getDataDrivenSubscriptionID() {
        return dataDrivenSubscriptionID;
    }
    
    public void setDataDrivenSubscriptionID(java.lang.String dataDrivenSubscriptionID) {
        this.dataDrivenSubscriptionID = dataDrivenSubscriptionID;
    }
    
    public org.jboss.test.webservice.jbws718.ExtensionSettings getExtensionSettings() {
        return extensionSettings;
    }
    
    public void setExtensionSettings(org.jboss.test.webservice.jbws718.ExtensionSettings extensionSettings) {
        this.extensionSettings = extensionSettings;
    }
    
    public javax.xml.soap.SOAPElement getDataRetrievalPlan() {
        return dataRetrievalPlan;
    }
    
    public void setDataRetrievalPlan(javax.xml.soap.SOAPElement dataRetrievalPlan) {
        this.dataRetrievalPlan = dataRetrievalPlan;
    }
    
    public java.lang.String getDescription() {
        return description;
    }
    
    public void setDescription(java.lang.String description) {
        this.description = description;
    }
    
    public java.lang.String getEventType() {
        return eventType;
    }
    
    public void setEventType(java.lang.String eventType) {
        this.eventType = eventType;
    }
    
    public java.lang.String getMatchData() {
        return matchData;
    }
    
    public void setMatchData(java.lang.String matchData) {
        this.matchData = matchData;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfParameterValueOrFieldReference getParameters() {
        return parameters;
    }
    
    public void setParameters(org.jboss.test.webservice.jbws718.ArrayOfParameterValueOrFieldReference parameters) {
        this.parameters = parameters;
    }
}
