// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class SetDataSourceContents {
    protected java.lang.String dataSource;
    protected org.jboss.test.webservice.jbws718.DataSourceDefinition definition;
    
    public SetDataSourceContents() {
    }
    
    public SetDataSourceContents(java.lang.String dataSource, org.jboss.test.webservice.jbws718.DataSourceDefinition definition) {
        this.dataSource = dataSource;
        this.definition = definition;
    }
    
    public java.lang.String getDataSource() {
        return dataSource;
    }
    
    public void setDataSource(java.lang.String dataSource) {
        this.dataSource = dataSource;
    }
    
    public org.jboss.test.webservice.jbws718.DataSourceDefinition getDefinition() {
        return definition;
    }
    
    public void setDefinition(org.jboss.test.webservice.jbws718.DataSourceDefinition definition) {
        this.definition = definition;
    }
}
