// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class SetPolicies {
    protected java.lang.String item;
    protected org.jboss.test.webservice.jbws718.ArrayOfPolicy policies;
    
    public SetPolicies() {
    }
    
    public SetPolicies(java.lang.String item, org.jboss.test.webservice.jbws718.ArrayOfPolicy policies) {
        this.item = item;
        this.policies = policies;
    }
    
    public java.lang.String getItem() {
        return item;
    }
    
    public void setItem(java.lang.String item) {
        this.item = item;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfPolicy getPolicies() {
        return policies;
    }
    
    public void setPolicies(org.jboss.test.webservice.jbws718.ArrayOfPolicy policies) {
        this.policies = policies;
    }
}
