// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class SetReportDataSources {
    protected java.lang.String report;
    protected org.jboss.test.webservice.jbws718.ArrayOfDataSource dataSources;
    
    public SetReportDataSources() {
    }
    
    public SetReportDataSources(java.lang.String report, org.jboss.test.webservice.jbws718.ArrayOfDataSource dataSources) {
        this.report = report;
        this.dataSources = dataSources;
    }
    
    public java.lang.String getReport() {
        return report;
    }
    
    public void setReport(java.lang.String report) {
        this.report = report;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfDataSource getDataSources() {
        return dataSources;
    }
    
    public void setDataSources(org.jboss.test.webservice.jbws718.ArrayOfDataSource dataSources) {
        this.dataSources = dataSources;
    }
}
