// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class SetReportDefinition {
    protected java.lang.String report;
    protected byte[] definition;
    
    public SetReportDefinition() {
    }
    
    public SetReportDefinition(java.lang.String report, byte[] definition) {
        this.report = report;
        this.definition = definition;
    }
    
    public java.lang.String getReport() {
        return report;
    }
    
    public void setReport(java.lang.String report) {
        this.report = report;
    }
    
    public byte[] getDefinition() {
        return definition;
    }
    
    public void setDefinition(byte[] definition) {
        this.definition = definition;
    }
}
