// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class SetResourceContents {
    protected java.lang.String resource;
    protected byte[] contents;
    protected java.lang.String mimeType;
    
    public SetResourceContents() {
    }
    
    public SetResourceContents(java.lang.String resource, byte[] contents, java.lang.String mimeType) {
        this.resource = resource;
        this.contents = contents;
        this.mimeType = mimeType;
    }
    
    public java.lang.String getResource() {
        return resource;
    }
    
    public void setResource(java.lang.String resource) {
        this.resource = resource;
    }
    
    public byte[] getContents() {
        return contents;
    }
    
    public void setContents(byte[] contents) {
        this.contents = contents;
    }
    
    public java.lang.String getMimeType() {
        return mimeType;
    }
    
    public void setMimeType(java.lang.String mimeType) {
        this.mimeType = mimeType;
    }
}
