// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class SetReportParameters {
    protected java.lang.String report;
    protected org.jboss.test.webservice.jbws718.ArrayOfReportParameter parameters;
    
    public SetReportParameters() {
    }
    
    public SetReportParameters(java.lang.String report, org.jboss.test.webservice.jbws718.ArrayOfReportParameter parameters) {
        this.report = report;
        this.parameters = parameters;
    }
    
    public java.lang.String getReport() {
        return report;
    }
    
    public void setReport(java.lang.String report) {
        this.report = report;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfReportParameter getParameters() {
        return parameters;
    }
    
    public void setParameters(org.jboss.test.webservice.jbws718.ArrayOfReportParameter parameters) {
        this.parameters = parameters;
    }
}
