// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class SetSystemPolicies {
    protected org.jboss.test.webservice.jbws718.ArrayOfPolicy policies;
    
    public SetSystemPolicies() {
    }
    
    public SetSystemPolicies(org.jboss.test.webservice.jbws718.ArrayOfPolicy policies) {
        this.policies = policies;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfPolicy getPolicies() {
        return policies;
    }
    
    public void setPolicies(org.jboss.test.webservice.jbws718.ArrayOfPolicy policies) {
        this.policies = policies;
    }
}
