// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class SetSubscriptionProperties {
    protected java.lang.String subscriptionID;
    protected org.jboss.test.webservice.jbws718.ExtensionSettings extensionSettings;
    protected java.lang.String description;
    protected java.lang.String eventType;
    protected java.lang.String matchData;
    protected org.jboss.test.webservice.jbws718.ArrayOfParameterValue parameters;
    
    public SetSubscriptionProperties() {
    }
    
    public SetSubscriptionProperties(java.lang.String subscriptionID, org.jboss.test.webservice.jbws718.ExtensionSettings extensionSettings, java.lang.String description, java.lang.String eventType, java.lang.String matchData, org.jboss.test.webservice.jbws718.ArrayOfParameterValue parameters) {
        this.subscriptionID = subscriptionID;
        this.extensionSettings = extensionSettings;
        this.description = description;
        this.eventType = eventType;
        this.matchData = matchData;
        this.parameters = parameters;
    }
    
    public java.lang.String getSubscriptionID() {
        return subscriptionID;
    }
    
    public void setSubscriptionID(java.lang.String subscriptionID) {
        this.subscriptionID = subscriptionID;
    }
    
    public org.jboss.test.webservice.jbws718.ExtensionSettings getExtensionSettings() {
        return extensionSettings;
    }
    
    public void setExtensionSettings(org.jboss.test.webservice.jbws718.ExtensionSettings extensionSettings) {
        this.extensionSettings = extensionSettings;
    }
    
    public java.lang.String getDescription() {
        return description;
    }
    
    public void setDescription(java.lang.String description) {
        this.description = description;
    }
    
    public java.lang.String getEventType() {
        return eventType;
    }
    
    public void setEventType(java.lang.String eventType) {
        this.eventType = eventType;
    }
    
    public java.lang.String getMatchData() {
        return matchData;
    }
    
    public void setMatchData(java.lang.String matchData) {
        this.matchData = matchData;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfParameterValue getParameters() {
        return parameters;
    }
    
    public void setParameters(org.jboss.test.webservice.jbws718.ArrayOfParameterValue parameters) {
        this.parameters = parameters;
    }
}
