// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class Subscription {
    protected java.lang.String subscriptionID;
    protected java.lang.String owner;
    protected java.lang.String path;
    protected java.lang.String virtualPath;
    protected java.lang.String report;
    protected org.jboss.test.webservice.jbws718.ExtensionSettings deliverySettings;
    protected java.lang.String description;
    protected java.lang.String status;
    protected org.jboss.test.webservice.jbws718.ActiveState active;
    protected java.util.Calendar lastExecuted;
    protected java.lang.String modifiedBy;
    protected java.util.Calendar modifiedDate;
    protected java.lang.String eventType;
    protected boolean isDataDriven;
    
    public Subscription() {
    }
    
    public Subscription(java.lang.String subscriptionID, java.lang.String owner, java.lang.String path, java.lang.String virtualPath, java.lang.String report, org.jboss.test.webservice.jbws718.ExtensionSettings deliverySettings, java.lang.String description, java.lang.String status, org.jboss.test.webservice.jbws718.ActiveState active, java.util.Calendar lastExecuted, java.lang.String modifiedBy, java.util.Calendar modifiedDate, java.lang.String eventType, boolean isDataDriven) {
        this.subscriptionID = subscriptionID;
        this.owner = owner;
        this.path = path;
        this.virtualPath = virtualPath;
        this.report = report;
        this.deliverySettings = deliverySettings;
        this.description = description;
        this.status = status;
        this.active = active;
        this.lastExecuted = lastExecuted;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
        this.eventType = eventType;
        this.isDataDriven = isDataDriven;
    }
    
    public java.lang.String getSubscriptionID() {
        return subscriptionID;
    }
    
    public void setSubscriptionID(java.lang.String subscriptionID) {
        this.subscriptionID = subscriptionID;
    }
    
    public java.lang.String getOwner() {
        return owner;
    }
    
    public void setOwner(java.lang.String owner) {
        this.owner = owner;
    }
    
    public java.lang.String getPath() {
        return path;
    }
    
    public void setPath(java.lang.String path) {
        this.path = path;
    }
    
    public java.lang.String getVirtualPath() {
        return virtualPath;
    }
    
    public void setVirtualPath(java.lang.String virtualPath) {
        this.virtualPath = virtualPath;
    }
    
    public java.lang.String getReport() {
        return report;
    }
    
    public void setReport(java.lang.String report) {
        this.report = report;
    }
    
    public org.jboss.test.webservice.jbws718.ExtensionSettings getDeliverySettings() {
        return deliverySettings;
    }
    
    public void setDeliverySettings(org.jboss.test.webservice.jbws718.ExtensionSettings deliverySettings) {
        this.deliverySettings = deliverySettings;
    }
    
    public java.lang.String getDescription() {
        return description;
    }
    
    public void setDescription(java.lang.String description) {
        this.description = description;
    }
    
    public java.lang.String getStatus() {
        return status;
    }
    
    public void setStatus(java.lang.String status) {
        this.status = status;
    }
    
    public org.jboss.test.webservice.jbws718.ActiveState getActive() {
        return active;
    }
    
    public void setActive(org.jboss.test.webservice.jbws718.ActiveState active) {
        this.active = active;
    }
    
    public java.util.Calendar getLastExecuted() {
        return lastExecuted;
    }
    
    public void setLastExecuted(java.util.Calendar lastExecuted) {
        this.lastExecuted = lastExecuted;
    }
    
    public java.lang.String getModifiedBy() {
        return modifiedBy;
    }
    
    public void setModifiedBy(java.lang.String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    
    public java.util.Calendar getModifiedDate() {
        return modifiedDate;
    }
    
    public void setModifiedDate(java.util.Calendar modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    
    public java.lang.String getEventType() {
        return eventType;
    }
    
    public void setEventType(java.lang.String eventType) {
        this.eventType = eventType;
    }
    
    public boolean isIsDataDriven() {
        return isDataDriven;
    }
    
    public void setIsDataDriven(boolean isDataDriven) {
        this.isDataDriven = isDataDriven;
    }
}
