// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ValidateExtensionSettings {
    protected java.lang.String extension;
    protected org.jboss.test.webservice.jbws718.ArrayOfParameterValueOrFieldReference parameterValues;
    
    public ValidateExtensionSettings() {
    }
    
    public ValidateExtensionSettings(java.lang.String extension, org.jboss.test.webservice.jbws718.ArrayOfParameterValueOrFieldReference parameterValues) {
        this.extension = extension;
        this.parameterValues = parameterValues;
    }
    
    public java.lang.String getExtension() {
        return extension;
    }
    
    public void setExtension(java.lang.String extension) {
        this.extension = extension;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfParameterValueOrFieldReference getParameterValues() {
        return parameterValues;
    }
    
    public void setParameterValues(org.jboss.test.webservice.jbws718.ArrayOfParameterValueOrFieldReference parameterValues) {
        this.parameterValues = parameterValues;
    }
}
