// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ValidateExtensionSettingsResponse {
    protected org.jboss.test.webservice.jbws718.ArrayOfExtensionParameter parameterErrors;
    
    public ValidateExtensionSettingsResponse() {
    }
    
    public ValidateExtensionSettingsResponse(org.jboss.test.webservice.jbws718.ArrayOfExtensionParameter parameterErrors) {
        this.parameterErrors = parameterErrors;
    }
    
    public org.jboss.test.webservice.jbws718.ArrayOfExtensionParameter getParameterErrors() {
        return parameterErrors;
    }
    
    public void setParameterErrors(org.jboss.test.webservice.jbws718.ArrayOfExtensionParameter parameterErrors) {
        this.parameterErrors = parameterErrors;
    }
}
