// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class ValidValue {
    protected java.lang.String label;
    protected java.lang.String value;
    
    public ValidValue() {
    }
    
    public ValidValue(java.lang.String label, java.lang.String value) {
        this.label = label;
        this.value = value;
    }
    
    public java.lang.String getLabel() {
        return label;
    }
    
    public void setLabel(java.lang.String label) {
        this.label = label;
    }
    
    public java.lang.String getValue() {
        return value;
    }
    
    public void setValue(java.lang.String value) {
        this.value = value;
    }
}
