// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws718;


public class Warning {
    protected java.lang.String code;
    protected java.lang.String severity;
    protected java.lang.String objectName;
    protected java.lang.String objectType;
    protected java.lang.String message;
    
    public Warning() {
    }
    
    public Warning(java.lang.String code, java.lang.String severity, java.lang.String objectName, java.lang.String objectType, java.lang.String message) {
        this.code = code;
        this.severity = severity;
        this.objectName = objectName;
        this.objectType = objectType;
        this.message = message;
    }
    
    public java.lang.String getCode() {
        return code;
    }
    
    public void setCode(java.lang.String code) {
        this.code = code;
    }
    
    public java.lang.String getSeverity() {
        return severity;
    }
    
    public void setSeverity(java.lang.String severity) {
        this.severity = severity;
    }
    
    public java.lang.String getObjectName() {
        return objectName;
    }
    
    public void setObjectName(java.lang.String objectName) {
        this.objectName = objectName;
    }
    
    public java.lang.String getObjectType() {
        return objectType;
    }
    
    public void setObjectType(java.lang.String objectType) {
        this.objectType = objectType;
    }
    
    public java.lang.String getMessage() {
        return message;
    }
    
    public void setMessage(java.lang.String message) {
        this.message = message;
    }
}
