// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws706;

public interface DemoServicePortType extends java.rmi.Remote {
    public org.jboss.test.webservice.jbws706.Descr processDescr(java.lang.String p) throws 
        org.jboss.test.webservice.jbws706.AlturaPostConditionException, org.jboss.test.webservice.jbws706.AlturaPreConditionException,  java.rmi.RemoteException;
}
