// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.jboss.test.webservice.marshalltest._arrays.javax.xml.namespace;


public class QNameArray {
    private javax.xml.namespace.QName[] value;
    
    public QNameArray() {
    }
    
    public QNameArray(javax.xml.namespace.QName[] sourceArray) {
        value = sourceArray;
    }
    
    public void fromArray(javax.xml.namespace.QName[] sourceArray) {
        this.value = sourceArray;
    }
    
    public javax.xml.namespace.QName[] toArray() {
        return value;
    }
    
    public javax.xml.namespace.QName[] getValue() {
        return value;
    }
    
    public void setValue(javax.xml.namespace.QName[] value) {
        this.value = value;
    }
}
