// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.jboss.test.webservice.marshalltest._arrays.java.math;


public class BigDecimalArray {
    private java.math.BigDecimal[] value;
    
    public BigDecimalArray() {
    }
    
    public BigDecimalArray(java.math.BigDecimal[] sourceArray) {
        value = sourceArray;
    }
    
    public void fromArray(java.math.BigDecimal[] sourceArray) {
        this.value = sourceArray;
    }
    
    public java.math.BigDecimal[] toArray() {
        return value;
    }
    
    public java.math.BigDecimal[] getValue() {
        return value;
    }
    
    public void setValue(java.math.BigDecimal[] value) {
        this.value = value;
    }
}
