// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.jboss.test.webservice.marshalltest._arrays.java.math;


public class BigIntegerArray {
    private java.math.BigInteger[] value;
    
    public BigIntegerArray() {
    }
    
    public BigIntegerArray(java.math.BigInteger[] sourceArray) {
        value = sourceArray;
    }
    
    public void fromArray(java.math.BigInteger[] sourceArray) {
        this.value = sourceArray;
    }
    
    public java.math.BigInteger[] toArray() {
        return value;
    }
    
    public java.math.BigInteger[] getValue() {
        return value;
    }
    
    public void setValue(java.math.BigInteger[] value) {
        this.value = value;
    }
}
