// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws751;


public class LoanTransactionHistory_Type {
    protected org.jboss.test.webservice.jbws751.LoanTransaction_Type[] transaction;
    
    public LoanTransactionHistory_Type() {
    }
    
    public LoanTransactionHistory_Type(org.jboss.test.webservice.jbws751.LoanTransaction_Type[] transaction) {
        this.transaction = transaction;
    }
    
    public org.jboss.test.webservice.jbws751.LoanTransaction_Type[] getTransaction() {
        return transaction;
    }
    
    public void setTransaction(org.jboss.test.webservice.jbws751.LoanTransaction_Type[] transaction) {
        this.transaction = transaction;
    }
}
