// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws751;


public class StatusRs extends java.lang.Exception {
    private java.lang.String sessionId;
    private java.lang.String code;
    private java.lang.String message;
    private java.lang.String type;
    
    
    public StatusRs(java.lang.String sessionId, java.lang.String code, java.lang.String message, java.lang.String type) {
        this.sessionId = sessionId;
        this.code = code;
        this.message = message;
        this.type = type;
    }
    
    public java.lang.String getSessionId() {
        return sessionId;
    }
    
    public java.lang.String getCode() {
        return code;
    }
    
    public java.lang.String getMessage() {
        return message;
    }
    
    public java.lang.String getType() {
        return type;
    }
}
