// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws751;


public class TransactionHistoryRs {
    protected java.lang.String sessionId;
    protected java.lang.Integer recordPointer;
    protected org.jboss.test.webservice.jbws751.ShareTransactionHistory_Type shareHistory;
    protected org.jboss.test.webservice.jbws751.LoanTransactionHistory_Type loanHistory;
    
    public TransactionHistoryRs() {
    }
    
    public TransactionHistoryRs(java.lang.String sessionId, java.lang.Integer recordPointer, org.jboss.test.webservice.jbws751.ShareTransactionHistory_Type shareHistory, org.jboss.test.webservice.jbws751.LoanTransactionHistory_Type loanHistory) {
        this.sessionId = sessionId;
        this.recordPointer = recordPointer;
        this.shareHistory = shareHistory;
        this.loanHistory = loanHistory;
    }
    
    public java.lang.String getSessionId() {
        return sessionId;
    }
    
    public void setSessionId(java.lang.String sessionId) {
        this.sessionId = sessionId;
    }
    
    public java.lang.Integer getRecordPointer() {
        return recordPointer;
    }
    
    public void setRecordPointer(java.lang.Integer recordPointer) {
        this.recordPointer = recordPointer;
    }
    
    public org.jboss.test.webservice.jbws751.ShareTransactionHistory_Type getShareHistory() {
        return shareHistory;
    }
    
    public void setShareHistory(org.jboss.test.webservice.jbws751.ShareTransactionHistory_Type shareHistory) {
        this.shareHistory = shareHistory;
    }
    
    public org.jboss.test.webservice.jbws751.LoanTransactionHistory_Type getLoanHistory() {
        return loanHistory;
    }
    
    public void setLoanHistory(org.jboss.test.webservice.jbws751.LoanTransactionHistory_Type loanHistory) {
        this.loanHistory = loanHistory;
    }
}
