// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws751;


public class TransactionHistoryRq {
    protected java.lang.String sessionId;
    protected java.lang.Integer recordPointer;
    protected java.lang.String memberNumber;
    protected short id;
    protected java.lang.String type;
    protected java.util.Calendar startDate;
    protected java.util.Calendar endDate;
    
    public TransactionHistoryRq() {
    }
    
    public TransactionHistoryRq(java.lang.String sessionId, java.lang.Integer recordPointer, java.lang.String memberNumber, short id, java.lang.String type, java.util.Calendar startDate, java.util.Calendar endDate) {
        this.sessionId = sessionId;
        this.recordPointer = recordPointer;
        this.memberNumber = memberNumber;
        this.id = id;
        this.type = type;
        this.startDate = startDate;
        this.endDate = endDate;
    }
    
    public java.lang.String getSessionId() {
        return sessionId;
    }
    
    public void setSessionId(java.lang.String sessionId) {
        this.sessionId = sessionId;
    }
    
    public java.lang.Integer getRecordPointer() {
        return recordPointer;
    }
    
    public void setRecordPointer(java.lang.Integer recordPointer) {
        this.recordPointer = recordPointer;
    }
    
    public java.lang.String getMemberNumber() {
        return memberNumber;
    }
    
    public void setMemberNumber(java.lang.String memberNumber) {
        this.memberNumber = memberNumber;
    }
    
    public short getId() {
        return id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    
    public java.lang.String getType() {
        return type;
    }
    
    public void setType(java.lang.String type) {
        this.type = type;
    }
    
    public java.util.Calendar getStartDate() {
        return startDate;
    }
    
    public void setStartDate(java.util.Calendar startDate) {
        this.startDate = startDate;
    }
    
    public java.util.Calendar getEndDate() {
        return endDate;
    }
    
    public void setEndDate(java.util.Calendar endDate) {
        this.endDate = endDate;
    }
}
