// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws663.holders;


public class ResponseInfoHolder implements javax.xml.rpc.holders.Holder {
    public org.jboss.test.webservice.jbws663.ResponseInfo value;
    
    public ResponseInfoHolder() {
    }
    
    public ResponseInfoHolder(org.jboss.test.webservice.jbws663.ResponseInfo myResponseInfo) {
        this.value = myResponseInfo;
    }
}
