// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws663.holders;


public class SubscriptionInfoHolder implements javax.xml.rpc.holders.Holder {
    public org.jboss.test.webservice.jbws663.SubscriptionInfo value;
    
    public SubscriptionInfoHolder() {
    }
    
    public SubscriptionInfoHolder(org.jboss.test.webservice.jbws663.SubscriptionInfo mySubscriptionInfo) {
        this.value = mySubscriptionInfo;
    }
}
