// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;


public class AccessDeniedFault extends Fault
{ 
   /** The serialVersionUID */
   private static final long serialVersionUID = 8192293619557190492L;

   public AccessDeniedFault()
   {
   } 
}
