// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class CacheControl implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = -1661199432288541278L;
   protected int expires;
   protected java.lang.String userScope;
   protected java.lang.String validateTag;
   protected Extension[] extensions;

   public CacheControl()
   {
   }

   public CacheControl(int expires, java.lang.String userScope, java.lang.String validateTag, Extension[] extensions)
   {
      this.expires = expires;
      this.userScope = userScope;
      this.validateTag = validateTag;
      this.extensions = extensions;
   }

   public int getExpires()
   {
      return expires;
   }

   public void setExpires(int expires)
   {
      this.expires = expires;
   }

   public java.lang.String getUserScope()
   {
      return userScope;
   }

   public void setUserScope(java.lang.String userScope)
   {
      this.userScope = userScope;
   }

   public java.lang.String getValidateTag()
   {
      return validateTag;
   }

   public void setValidateTag(java.lang.String validateTag)
   {
      this.validateTag = validateTag;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
