// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class ClientData implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = -5993549215645249105L;
   protected java.lang.String userAgent;
   protected Extension[] extensions;

   public ClientData()
   {
   }

   public ClientData(java.lang.String userAgent, Extension[] extensions)
   {
      this.userAgent = userAgent;
      this.extensions = extensions;
   }

   public java.lang.String getUserAgent()
   {
      return userAgent;
   }

   public void setUserAgent(java.lang.String userAgent)
   {
      this.userAgent = userAgent;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
