// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class ClonePortlet implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = -3629786318393192297L;
   protected RegistrationContext registrationContext;
   protected PortletContext portletContext;
   protected UserContext userContext;

   public ClonePortlet()
   {
   }

   public ClonePortlet(RegistrationContext registrationContext, PortletContext portletContext, UserContext userContext)
   {
      this.registrationContext = registrationContext;
      this.portletContext = portletContext;
      this.userContext = userContext;
   }

   public RegistrationContext getRegistrationContext()
   {
      return registrationContext;
   }

   public void setRegistrationContext(RegistrationContext registrationContext)
   {
      this.registrationContext = registrationContext;
   }

   public PortletContext getPortletContext()
   {
      return portletContext;
   }

   public void setPortletContext(PortletContext portletContext)
   {
      this.portletContext = portletContext;
   }

   public UserContext getUserContext()
   {
      return userContext;
   }

   public void setUserContext(UserContext userContext)
   {
      this.userContext = userContext;
   }
}
