// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class Contact implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = 8877254457698689441L;
   protected Postal postal;
   protected Telecom telecom;
   protected Online online;
   protected Extension[] extensions;

   public Contact()
   {
   }

   public Contact(Postal postal, Telecom telecom, Online online, Extension[] extensions)
   {
      this.postal = postal;
      this.telecom = telecom;
      this.online = online;
      this.extensions = extensions;
   }

   public Postal getPostal()
   {
      return postal;
   }

   public void setPostal(Postal postal)
   {
      this.postal = postal;
   }

   public Telecom getTelecom()
   {
      return telecom;
   }

   public void setTelecom(Telecom telecom)
   {
      this.telecom = telecom;
   }

   public Online getOnline()
   {
      return online;
   }

   public void setOnline(Online online)
   {
      this.online = online;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
