// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class DestroyPortlets implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = -1508438688113822859L;
   protected RegistrationContext registrationContext;
   protected java.lang.String[] portletHandles;

   public DestroyPortlets()
   {
   }

   public DestroyPortlets(RegistrationContext registrationContext, java.lang.String[] portletHandles)
   {
      this.registrationContext = registrationContext;
      this.portletHandles = portletHandles;
   }

   public RegistrationContext getRegistrationContext()
   {
      return registrationContext;
   }

   public void setRegistrationContext(RegistrationContext registrationContext)
   {
      this.registrationContext = registrationContext;
   }

   public java.lang.String[] getPortletHandles()
   {
      return portletHandles;
   }

   public void setPortletHandles(java.lang.String[] portletHandles)
   {
      this.portletHandles = portletHandles;
   }
}
