// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class DestroyPortletsResponse implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = -6246599747206154636L;
   protected DestroyFailed[] destroyFailed;
   protected Extension[] extensions;

   public DestroyPortletsResponse()
   {
   }

   public DestroyPortletsResponse(DestroyFailed[] destroyFailed, Extension[] extensions)
   {
      this.destroyFailed = destroyFailed;
      this.extensions = extensions;
   }

   public DestroyFailed[] getDestroyFailed()
   {
      return destroyFailed;
   }

   public void setDestroyFailed(DestroyFailed[] destroyFailed)
   {
      this.destroyFailed = destroyFailed;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
