// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class DestroyFailed implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = 5473237648959918416L;
   protected java.lang.String portletHandle;
   protected java.lang.String reason;

   public DestroyFailed()
   {
   }

   public DestroyFailed(java.lang.String portletHandle, java.lang.String reason)
   {
      this.portletHandle = portletHandle;
      this.reason = reason;
   }

   public java.lang.String getPortletHandle()
   {
      return portletHandle;
   }

   public void setPortletHandle(java.lang.String portletHandle)
   {
      this.portletHandle = portletHandle;
   }

   public java.lang.String getReason()
   {
      return reason;
   }

   public void setReason(java.lang.String reason)
   {
      this.reason = reason;
   }
}
