// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class EmployerInfo implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = -8042104476141761313L;
   protected java.lang.String employer;
   protected java.lang.String department;
   protected java.lang.String jobtitle;
   protected Extension[] extensions;

   public EmployerInfo()
   {
   }

   public EmployerInfo(java.lang.String employer, java.lang.String department, java.lang.String jobtitle, Extension[] extensions)
   {
      this.employer = employer;
      this.department = department;
      this.jobtitle = jobtitle;
      this.extensions = extensions;
   }

   public java.lang.String getEmployer()
   {
      return employer;
   }

   public void setEmployer(java.lang.String employer)
   {
      this.employer = employer;
   }

   public java.lang.String getDepartment()
   {
      return department;
   }

   public void setDepartment(java.lang.String department)
   {
      this.department = department;
   }

   public java.lang.String getJobtitle()
   {
      return jobtitle;
   }

   public void setJobtitle(java.lang.String jobtitle)
   {
      this.jobtitle = jobtitle;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
