// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class GetMarkup implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = -5698998107394904886L;
   protected RegistrationContext registrationContext;
   protected PortletContext portletContext;
   protected RuntimeContext runtimeContext;
   protected UserContext userContext;
   protected MarkupParams markupParams;

   public GetMarkup()
   {
   }

   public GetMarkup(RegistrationContext registrationContext, PortletContext portletContext, RuntimeContext runtimeContext, UserContext userContext, MarkupParams markupParams)
   {
      this.registrationContext = registrationContext;
      this.portletContext = portletContext;
      this.runtimeContext = runtimeContext;
      this.userContext = userContext;
      this.markupParams = markupParams;
   }

   public RegistrationContext getRegistrationContext()
   {
      return registrationContext;
   }

   public void setRegistrationContext(RegistrationContext registrationContext)
   {
      this.registrationContext = registrationContext;
   }

   public PortletContext getPortletContext()
   {
      return portletContext;
   }

   public void setPortletContext(PortletContext portletContext)
   {
      this.portletContext = portletContext;
   }

   public RuntimeContext getRuntimeContext()
   {
      return runtimeContext;
   }

   public void setRuntimeContext(RuntimeContext runtimeContext)
   {
      this.runtimeContext = runtimeContext;
   }

   public UserContext getUserContext()
   {
      return userContext;
   }

   public void setUserContext(UserContext userContext)
   {
      this.userContext = userContext;
   }

   public MarkupParams getMarkupParams()
   {
      return markupParams;
   }

   public void setMarkupParams(MarkupParams markupParams)
   {
      this.markupParams = markupParams;
   }
}
