// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class InitCookie implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = -5131790187292927458L;
   protected RegistrationContext registrationContext;

   public InitCookie()
   {
   }

   public InitCookie(RegistrationContext registrationContext)
   {
      this.registrationContext = registrationContext;
   }

   public RegistrationContext getRegistrationContext()
   {
      return registrationContext;
   }

   public void setRegistrationContext(RegistrationContext registrationContext)
   {
      this.registrationContext = registrationContext;
   }
}
