// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;


public class InteractionParams
{
   protected StateChange portletStateChange;
   protected java.lang.String interactionState;
   protected NamedString[] formParameters;
   protected UploadContext[] uploadContexts;
   protected Extension[] extensions;

   public InteractionParams()
   {
   }

   public InteractionParams(StateChange portletStateChange, java.lang.String interactionState, NamedString[] formParameters, UploadContext[] uploadContexts, Extension[] extensions)
   {
      this.portletStateChange = portletStateChange;
      this.interactionState = interactionState;
      this.formParameters = formParameters;
      this.uploadContexts = uploadContexts;
      this.extensions = extensions;
   }

   public StateChange getPortletStateChange()
   {
      return portletStateChange;
   }

   public void setPortletStateChange(StateChange portletStateChange)
   {
      this.portletStateChange = portletStateChange;
   }

   public java.lang.String getInteractionState()
   {
      return interactionState;
   }

   public void setInteractionState(java.lang.String interactionState)
   {
      this.interactionState = interactionState;
   }

   public NamedString[] getFormParameters()
   {
      return formParameters;
   }

   public void setFormParameters(NamedString[] formParameters)
   {
      this.formParameters = formParameters;
   }

   public UploadContext[] getUploadContexts()
   {
      return uploadContexts;
   }

   public void setUploadContexts(UploadContext[] uploadContexts)
   {
      this.uploadContexts = uploadContexts;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
