// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class ItemDescription implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = 428082530776438599L;
   protected java.lang.String itemName;
   protected LocalizedString description;
   protected Extension[] extensions;

   public ItemDescription()
   {
   }

   public ItemDescription(java.lang.String itemName, LocalizedString description, Extension[] extensions)
   {
      this.itemName = itemName;
      this.description = description;
      this.extensions = extensions;
   }

   public java.lang.String getItemName()
   {
      return itemName;
   }

   public void setItemName(java.lang.String itemName)
   {
      this.itemName = itemName;
   }

   public LocalizedString getDescription()
   {
      return description;
   }

   public void setDescription(LocalizedString description)
   {
      this.description = description;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
