// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class LocalizedString implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = -6152621642103602376L;
   protected java.lang.String lang;
   protected java.lang.String resourceName;
   protected java.lang.String value;

   public LocalizedString()
   {
   }

   public LocalizedString(java.lang.String lang, java.lang.String resourceName, java.lang.String value)
   {
      this.lang = lang;
      this.resourceName = resourceName;
      this.value = value;
   }

   public java.lang.String getLang()
   {
      return lang;
   }

   public void setLang(java.lang.String lang)
   {
      this.lang = lang;
   }

   public java.lang.String getResourceName()
   {
      return resourceName;
   }

   public void setResourceName(java.lang.String resourceName)
   {
      this.resourceName = resourceName;
   }

   public java.lang.String getValue()
   {
      return value;
   }

   public void setValue(java.lang.String value)
   {
      this.value = value;
   }
}
