// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class MarkupType implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = -1206340318327754517L;
   protected java.lang.String mimeType;
   protected java.lang.String[] modes;
   protected java.lang.String[] windowStates;
   protected java.lang.String[] locales;
   protected Extension[] extensions;

   public MarkupType()
   {
   }

   public MarkupType(java.lang.String mimeType, java.lang.String[] modes, java.lang.String[] windowStates, java.lang.String[] locales, Extension[] extensions)
   {
      this.mimeType = mimeType;
      this.modes = modes;
      this.windowStates = windowStates;
      this.locales = locales;
      this.extensions = extensions;
   }

   public java.lang.String getMimeType()
   {
      return mimeType;
   }

   public void setMimeType(java.lang.String mimeType)
   {
      this.mimeType = mimeType;
   }

   public java.lang.String[] getModes()
   {
      return modes;
   }

   public void setModes(java.lang.String[] modes)
   {
      this.modes = modes;
   }

   public java.lang.String[] getWindowStates()
   {
      return windowStates;
   }

   public void setWindowStates(java.lang.String[] windowStates)
   {
      this.windowStates = windowStates;
   }

   public java.lang.String[] getLocales()
   {
      return locales;
   }

   public void setLocales(java.lang.String[] locales)
   {
      this.locales = locales;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
