// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class MarkupResponse implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = -3715184733896042795L;
   protected MarkupContext markupContext;
   protected SessionContext sessionContext;
   protected Extension[] extensions;

   public MarkupResponse()
   {
   }

   public MarkupResponse(MarkupContext markupContext, SessionContext sessionContext, Extension[] extensions)
   {
      this.markupContext = markupContext;
      this.sessionContext = sessionContext;
      this.extensions = extensions;
   }

   public MarkupContext getMarkupContext()
   {
      return markupContext;
   }

   public void setMarkupContext(MarkupContext markupContext)
   {
      this.markupContext = markupContext;
   }

   public SessionContext getSessionContext()
   {
      return sessionContext;
   }

   public void setSessionContext(SessionContext sessionContext)
   {
      this.sessionContext = sessionContext;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
