// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class ModelDescription implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = 2869665586382634816L;
   protected PropertyDescription[] propertyDescriptions;
   protected ModelTypes modelTypes;
   protected Extension[] extensions;

   public ModelDescription()
   {
   }

   public ModelDescription(PropertyDescription[] propertyDescriptions, ModelTypes modelTypes, Extension[] extensions)
   {
      this.propertyDescriptions = propertyDescriptions;
      this.modelTypes = modelTypes;
      this.extensions = extensions;
   }

   public PropertyDescription[] getPropertyDescriptions()
   {
      return propertyDescriptions;
   }

   public void setPropertyDescriptions(PropertyDescription[] propertyDescriptions)
   {
      this.propertyDescriptions = propertyDescriptions;
   }

   public ModelTypes getModelTypes()
   {
      return modelTypes;
   }

   public void setModelTypes(ModelTypes modelTypes)
   {
      this.modelTypes = modelTypes;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
