// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class ModifyRegistration implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = 8440327853527138068L;
   protected RegistrationContext registrationContext;
   protected RegistrationData registrationData;

   public ModifyRegistration()
   {
   }

   public ModifyRegistration(RegistrationContext registrationContext, RegistrationData registrationData)
   {
      this.registrationContext = registrationContext;
      this.registrationData = registrationData;
   }

   public RegistrationContext getRegistrationContext()
   {
      return registrationContext;
   }

   public void setRegistrationContext(RegistrationContext registrationContext)
   {
      this.registrationContext = registrationContext;
   }

   public RegistrationData getRegistrationData()
   {
      return registrationData;
   }

   public void setRegistrationData(RegistrationData registrationData)
   {
      this.registrationData = registrationData;
   }
}
