// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class NamedString implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = 5883640858629107000L;
   protected java.lang.String name;
   protected java.lang.String value;

   public NamedString()
   {
   }

   public NamedString(java.lang.String name, java.lang.String value)
   {
      this.name = name;
      this.value = value;
   }

   public java.lang.String getName()
   {
      return name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getValue()
   {
      return value;
   }

   public void setValue(java.lang.String value)
   {
      this.value = value;
   }
}
