// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class Online implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = 7777281436851187045L;
   protected java.lang.String email;
   protected java.lang.String uri;
   protected Extension[] extensions;

   public Online()
   {
   }

   public Online(java.lang.String email, java.lang.String uri, Extension[] extensions)
   {
      this.email = email;
      this.uri = uri;
      this.extensions = extensions;
   }

   public java.lang.String getEmail()
   {
      return email;
   }

   public void setEmail(java.lang.String email)
   {
      this.email = email;
   }

   public java.lang.String getUri()
   {
      return uri;
   }

   public void setUri(java.lang.String uri)
   {
      this.uri = uri;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
