// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


/**
 * [R] Handle	portletHandle
 * [R] MarkupType	markupTypes[]
 * [O] ID	groupID
 * [O] LocalizedString	description
 * [O] LocalizedString	shortTitle
 * [O] LocalizedString	title
 * [O] LocalizedString	displayName
 * [O] LocalizedString	keywords[]
 * [O] string	userCategories[]
 * [O] string	userProfileItems[]
 * [O] boolean	usesMethodGet
 * [O] boolean	defaultMarkupSecure
 * [O] boolean	onlySecure
 * [O] boolean	userContextStoredInSession
 * [O] boolean	templatesStoredInSession
 * [O] boolean	hasUserSpecificState
 * [O] boolean	doesUrlTemplateProcessing
 * [O] Extension	extensions
 */
public class PortletDescription implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = 1879738655613199243L;
   protected java.lang.String portletHandle;
   protected MarkupType[] markupTypes;
   protected java.lang.String groupID;
   protected LocalizedString description;
   protected LocalizedString shortTitle;
   protected LocalizedString title;
   protected LocalizedString displayName;
   protected LocalizedString[] keywords;
   protected java.lang.String[] userCategories;
   protected java.lang.String[] userProfileItems;
   protected java.lang.Boolean usesMethodGet;
   protected java.lang.Boolean defaultMarkupSecure;
   protected java.lang.Boolean onlySecure;
   protected java.lang.Boolean userContextStoredInSession;
   protected java.lang.Boolean templatesStoredInSession;
   protected java.lang.Boolean hasUserSpecificState;
   protected java.lang.Boolean doesUrlTemplateProcessing;
   protected Extension[] extensions;

   public PortletDescription()
   {
   }

   public PortletDescription(java.lang.String portletHandle, MarkupType[] markupTypes, java.lang.String groupID, LocalizedString description, LocalizedString shortTitle, LocalizedString title, LocalizedString displayName, LocalizedString[] keywords, java.lang.String[] userCategories, java.lang.String[] userProfileItems, java.lang.Boolean usesMethodGet, java.lang.Boolean defaultMarkupSecure, java.lang.Boolean onlySecure, java.lang.Boolean userContextStoredInSession, java.lang.Boolean templatesStoredInSession, java.lang.Boolean hasUserSpecificState, java.lang.Boolean doesUrlTemplateProcessing, Extension[] extensions)
   {
      this.portletHandle = portletHandle;
      this.markupTypes = markupTypes;
      this.groupID = groupID;
      this.description = description;
      this.shortTitle = shortTitle;
      this.title = title;
      this.displayName = displayName;
      this.keywords = keywords;
      this.userCategories = userCategories;
      this.userProfileItems = userProfileItems;
      this.usesMethodGet = usesMethodGet;
      this.defaultMarkupSecure = defaultMarkupSecure;
      this.onlySecure = onlySecure;
      this.userContextStoredInSession = userContextStoredInSession;
      this.templatesStoredInSession = templatesStoredInSession;
      this.hasUserSpecificState = hasUserSpecificState;
      this.doesUrlTemplateProcessing = doesUrlTemplateProcessing;
      this.extensions = extensions;
   }

   public java.lang.String getPortletHandle()
   {
      return portletHandle;
   }

   public void setPortletHandle(java.lang.String portletHandle)
   {
      this.portletHandle = portletHandle;
   }

   public MarkupType[] getMarkupTypes()
   {
      return markupTypes;
   }

   public void setMarkupTypes(MarkupType[] markupTypes)
   {
      this.markupTypes = markupTypes;
   }

   public java.lang.String getGroupID()
   {
      return groupID;
   }

   public void setGroupID(java.lang.String groupID)
   {
      this.groupID = groupID;
   }

   public LocalizedString getDescription()
   {
      return description;
   }

   public void setDescription(LocalizedString description)
   {
      this.description = description;
   }

   public LocalizedString getShortTitle()
   {
      return shortTitle;
   }

   public void setShortTitle(LocalizedString shortTitle)
   {
      this.shortTitle = shortTitle;
   }

   public LocalizedString getTitle()
   {
      return title;
   }

   public void setTitle(LocalizedString title)
   {
      this.title = title;
   }

   public LocalizedString getDisplayName()
   {
      return displayName;
   }

   public void setDisplayName(LocalizedString displayName)
   {
      this.displayName = displayName;
   }

   public LocalizedString[] getKeywords()
   {
      return keywords;
   }

   public void setKeywords(LocalizedString[] keywords)
   {
      this.keywords = keywords;
   }

   public java.lang.String[] getUserCategories()
   {
      return userCategories;
   }

   public void setUserCategories(java.lang.String[] userCategories)
   {
      this.userCategories = userCategories;
   }

   public java.lang.String[] getUserProfileItems()
   {
      return userProfileItems;
   }

   public void setUserProfileItems(java.lang.String[] userProfileItems)
   {
      this.userProfileItems = userProfileItems;
   }

   public java.lang.Boolean getUsesMethodGet()
   {
      return usesMethodGet;
   }

   public void setUsesMethodGet(java.lang.Boolean usesMethodGet)
   {
      this.usesMethodGet = usesMethodGet;
   }

   public java.lang.Boolean getDefaultMarkupSecure()
   {
      return defaultMarkupSecure;
   }

   public void setDefaultMarkupSecure(java.lang.Boolean defaultMarkupSecure)
   {
      this.defaultMarkupSecure = defaultMarkupSecure;
   }

   public java.lang.Boolean getOnlySecure()
   {
      return onlySecure;
   }

   public void setOnlySecure(java.lang.Boolean onlySecure)
   {
      this.onlySecure = onlySecure;
   }

   public java.lang.Boolean getUserContextStoredInSession()
   {
      return userContextStoredInSession;
   }

   public void setUserContextStoredInSession(java.lang.Boolean userContextStoredInSession)
   {
      this.userContextStoredInSession = userContextStoredInSession;
   }

   public java.lang.Boolean getTemplatesStoredInSession()
   {
      return templatesStoredInSession;
   }

   public void setTemplatesStoredInSession(java.lang.Boolean templatesStoredInSession)
   {
      this.templatesStoredInSession = templatesStoredInSession;
   }

   public java.lang.Boolean getHasUserSpecificState()
   {
      return hasUserSpecificState;
   }

   public void setHasUserSpecificState(java.lang.Boolean hasUserSpecificState)
   {
      this.hasUserSpecificState = hasUserSpecificState;
   }

   public java.lang.Boolean getDoesUrlTemplateProcessing()
   {
      return doesUrlTemplateProcessing;
   }

   public void setDoesUrlTemplateProcessing(java.lang.Boolean doesUrlTemplateProcessing)
   {
      this.doesUrlTemplateProcessing = doesUrlTemplateProcessing;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
