// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class PortletDescriptionResponse implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = -7232816944501501839L;
   protected PortletDescription portletDescription;
   protected ResourceList resourceList;
   protected Extension[] extensions;

   public PortletDescriptionResponse()
   {
   }

   public PortletDescriptionResponse(PortletDescription portletDescription, ResourceList resourceList, Extension[] extensions)
   {
      this.portletDescription = portletDescription;
      this.resourceList = resourceList;
      this.extensions = extensions;
   }

   public PortletDescription getPortletDescription()
   {
      return portletDescription;
   }

   public void setPortletDescription(PortletDescription portletDescription)
   {
      this.portletDescription = portletDescription;
   }

   public ResourceList getResourceList()
   {
      return resourceList;
   }

   public void setResourceList(ResourceList resourceList)
   {
      this.resourceList = resourceList;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
