// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class PortletContext implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = -7400121332070101590L;
   protected java.lang.String portletHandle;
   protected byte[] portletState;
   protected Extension[] extensions;

   public PortletContext()
   {
   }

   public PortletContext(java.lang.String portletHandle, byte[] portletState, Extension[] extensions)
   {
      this.portletHandle = portletHandle;
      this.portletState = portletState;
      this.extensions = extensions;
   }

   public java.lang.String getPortletHandle()
   {
      return portletHandle;
   }

   public void setPortletHandle(java.lang.String portletHandle)
   {
      this.portletHandle = portletHandle;
   }

   public byte[] getPortletState()
   {
      return portletState;
   }

   public void setPortletState(byte[] portletState)
   {
      this.portletState = portletState;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
