// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class PortletPropertyDescriptionResponse implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = 8122590096393067351L;
   protected ModelDescription modelDescription;
   protected ResourceList resourceList;
   protected Extension[] extensions;

   public PortletPropertyDescriptionResponse()
   {
   }

   public PortletPropertyDescriptionResponse(ModelDescription modelDescription, ResourceList resourceList, Extension[] extensions)
   {
      this.modelDescription = modelDescription;
      this.resourceList = resourceList;
      this.extensions = extensions;
   }

   public ModelDescription getModelDescription()
   {
      return modelDescription;
   }

   public void setModelDescription(ModelDescription modelDescription)
   {
      this.modelDescription = modelDescription;
   }

   public ResourceList getResourceList()
   {
      return resourceList;
   }

   public void setResourceList(ResourceList resourceList)
   {
      this.resourceList = resourceList;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
