// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class Postal implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = -3088707340009052712L;
   protected java.lang.String name;
   protected java.lang.String street;
   protected java.lang.String city;
   protected java.lang.String stateprov;
   protected java.lang.String postalcode;
   protected java.lang.String country;
   protected java.lang.String organization;
   protected Extension[] extensions;

   public Postal()
   {
   }

   public Postal(java.lang.String name, java.lang.String street, java.lang.String city, java.lang.String stateprov, java.lang.String postalcode, java.lang.String country, java.lang.String organization, Extension[] extensions)
   {
      this.name = name;
      this.street = street;
      this.city = city;
      this.stateprov = stateprov;
      this.postalcode = postalcode;
      this.country = country;
      this.organization = organization;
      this.extensions = extensions;
   }

   public java.lang.String getName()
   {
      return name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getStreet()
   {
      return street;
   }

   public void setStreet(java.lang.String street)
   {
      this.street = street;
   }

   public java.lang.String getCity()
   {
      return city;
   }

   public void setCity(java.lang.String city)
   {
      this.city = city;
   }

   public java.lang.String getStateprov()
   {
      return stateprov;
   }

   public void setStateprov(java.lang.String stateprov)
   {
      this.stateprov = stateprov;
   }

   public java.lang.String getPostalcode()
   {
      return postalcode;
   }

   public void setPostalcode(java.lang.String postalcode)
   {
      this.postalcode = postalcode;
   }

   public java.lang.String getCountry()
   {
      return country;
   }

   public void setCountry(java.lang.String country)
   {
      this.country = country;
   }

   public java.lang.String getOrganization()
   {
      return organization;
   }

   public void setOrganization(java.lang.String organization)
   {
      this.organization = organization;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
