// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class PropertyDescription implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = -9015093605452269811L;
   protected java.lang.String name;
   protected javax.xml.namespace.QName type;
   protected LocalizedString label;
   protected LocalizedString hint;
   protected Extension[] extensions;

   public PropertyDescription()
   {
   }

   public PropertyDescription(java.lang.String name, javax.xml.namespace.QName type, LocalizedString label, LocalizedString hint, Extension[] extensions)
   {
      this.name = name;
      this.type = type;
      this.label = label;
      this.hint = hint;
      this.extensions = extensions;
   }

   public java.lang.String getName()
   {
      return name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public javax.xml.namespace.QName getType()
   {
      return type;
   }

   public void setType(javax.xml.namespace.QName type)
   {
      this.type = type;
   }

   public LocalizedString getLabel()
   {
      return label;
   }

   public void setLabel(LocalizedString label)
   {
      this.label = label;
   }

   public LocalizedString getHint()
   {
      return hint;
   }

   public void setHint(LocalizedString hint)
   {
      this.hint = hint;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
