// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class Property implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = -8181987824499269919L;
   protected java.lang.String name;
   protected java.lang.String lang;
   protected java.lang.String stringValue;
   protected javax.xml.soap.SOAPElement[] _any;

   public Property()
   {
   }

   public Property(java.lang.String name, java.lang.String lang, java.lang.String stringValue, javax.xml.soap.SOAPElement[] _any)
   {
      this.name = name;
      this.lang = lang;
      this.stringValue = stringValue;
      this._any = _any;
   }

   public java.lang.String getName()
   {
      return name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getLang()
   {
      return lang;
   }

   public void setLang(java.lang.String lang)
   {
      this.lang = lang;
   }

   public java.lang.String getStringValue()
   {
      return stringValue;
   }

   public void setStringValue(java.lang.String stringValue)
   {
      this.stringValue = stringValue;
   }

   public javax.xml.soap.SOAPElement[] get_any()
   {
      return _any;
   }

   public void set_any(javax.xml.soap.SOAPElement[] _any)
   {
      this._any = _any;
   }
}
