// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class PropertyList implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = -6498747289908076641L;
   protected Property[] properties;
   protected ResetProperty[] resetProperties;
   protected Extension[] extensions;

   public PropertyList()
   {
   }

   public PropertyList(Property[] properties, ResetProperty[] resetProperties, Extension[] extensions)
   {
      this.properties = properties;
      this.resetProperties = resetProperties;
      this.extensions = extensions;
   }

   public Property[] getProperties()
   {
      return properties;
   }

   public void setProperties(Property[] properties)
   {
      this.properties = properties;
   }

   public ResetProperty[] getResetProperties()
   {
      return resetProperties;
   }

   public void setResetProperties(ResetProperty[] resetProperties)
   {
      this.resetProperties = resetProperties;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
