// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class RegistrationContext implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = 669872257303689288L;
   protected java.lang.String registrationHandle;
   protected byte[] registrationState;
   protected Extension[] extensions;

   public RegistrationContext()
   {
   }

   public RegistrationContext(java.lang.String registrationHandle, byte[] registrationState, Extension[] extensions)
   {
      this.registrationHandle = registrationHandle;
      this.registrationState = registrationState;
      this.extensions = extensions;
   }

   public java.lang.String getRegistrationHandle()
   {
      return registrationHandle;
   }

   public void setRegistrationHandle(java.lang.String registrationHandle)
   {
      this.registrationHandle = registrationHandle;
   }

   public byte[] getRegistrationState()
   {
      return registrationState;
   }

   public void setRegistrationState(byte[] registrationState)
   {
      this.registrationState = registrationState;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
