// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class RegistrationData implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = -4792547790487325232L;
   protected java.lang.String consumerName;
   protected java.lang.String consumerAgent;
   protected boolean methodGetSupported;
   protected java.lang.String[] consumerModes;
   protected java.lang.String[] consumerWindowStates;
   protected java.lang.String[] consumerUserScopes;
   protected java.lang.String[] customUserProfileData;
   protected Property[] registrationProperties;
   protected Extension[] extensions;

   public RegistrationData()
   {
   }

   public RegistrationData(java.lang.String consumerName, java.lang.String consumerAgent, boolean methodGetSupported, java.lang.String[] consumerModes, java.lang.String[] consumerWindowStates, java.lang.String[] consumerUserScopes, java.lang.String[] customUserProfileData, Property[] registrationProperties, Extension[] extensions)
   {
      this.consumerName = consumerName;
      this.consumerAgent = consumerAgent;
      this.methodGetSupported = methodGetSupported;
      this.consumerModes = consumerModes;
      this.consumerWindowStates = consumerWindowStates;
      this.consumerUserScopes = consumerUserScopes;
      this.customUserProfileData = customUserProfileData;
      this.registrationProperties = registrationProperties;
      this.extensions = extensions;
   }

   public java.lang.String getConsumerName()
   {
      return consumerName;
   }

   public void setConsumerName(java.lang.String consumerName)
   {
      this.consumerName = consumerName;
   }

   public java.lang.String getConsumerAgent()
   {
      return consumerAgent;
   }

   public void setConsumerAgent(java.lang.String consumerAgent)
   {
      this.consumerAgent = consumerAgent;
   }

   public boolean isMethodGetSupported()
   {
      return methodGetSupported;
   }

   public void setMethodGetSupported(boolean methodGetSupported)
   {
      this.methodGetSupported = methodGetSupported;
   }

   public java.lang.String[] getConsumerModes()
   {
      return consumerModes;
   }

   public void setConsumerModes(java.lang.String[] consumerModes)
   {
      this.consumerModes = consumerModes;
   }

   public java.lang.String[] getConsumerWindowStates()
   {
      return consumerWindowStates;
   }

   public void setConsumerWindowStates(java.lang.String[] consumerWindowStates)
   {
      this.consumerWindowStates = consumerWindowStates;
   }

   public java.lang.String[] getConsumerUserScopes()
   {
      return consumerUserScopes;
   }

   public void setConsumerUserScopes(java.lang.String[] consumerUserScopes)
   {
      this.consumerUserScopes = consumerUserScopes;
   }

   public java.lang.String[] getCustomUserProfileData()
   {
      return customUserProfileData;
   }

   public void setCustomUserProfileData(java.lang.String[] customUserProfileData)
   {
      this.customUserProfileData = customUserProfileData;
   }

   public Property[] getRegistrationProperties()
   {
      return registrationProperties;
   }

   public void setRegistrationProperties(Property[] registrationProperties)
   {
      this.registrationProperties = registrationProperties;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
