// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class RegistrationState implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = 8109782856632872891L;
   protected byte[] registrationState;
   protected Extension[] extensions;

   public RegistrationState()
   {
   }

   public RegistrationState(byte[] registrationState, Extension[] extensions)
   {
      this.registrationState = registrationState;
      this.extensions = extensions;
   }

   public byte[] getRegistrationState()
   {
      return registrationState;
   }

   public void setRegistrationState(byte[] registrationState)
   {
      this.registrationState = registrationState;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
