// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class ReleaseSessions implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = 2180804897524371397L;
   protected RegistrationContext registrationContext;
   protected java.lang.String[] sessionIDs;

   public ReleaseSessions()
   {
   }

   public ReleaseSessions(RegistrationContext registrationContext, java.lang.String[] sessionIDs)
   {
      this.registrationContext = registrationContext;
      this.sessionIDs = sessionIDs;
   }

   public RegistrationContext getRegistrationContext()
   {
      return registrationContext;
   }

   public void setRegistrationContext(RegistrationContext registrationContext)
   {
      this.registrationContext = registrationContext;
   }

   public java.lang.String[] getSessionIDs()
   {
      return sessionIDs;
   }

   public void setSessionIDs(java.lang.String[] sessionIDs)
   {
      this.sessionIDs = sessionIDs;
   }
}
