// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class ResetProperty implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = -4648037678127722097L;
   protected java.lang.String name;

   public ResetProperty()
   {
   }

   public ResetProperty(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getName()
   {
      return name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }
}
