// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class ResourceValue implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = -4866184353914054460L;
   protected java.lang.String lang;
   protected java.lang.String value;
   protected Extension[] extensions;

   public ResourceValue()
   {
   }

   public ResourceValue(java.lang.String lang, java.lang.String value, Extension[] extensions)
   {
      this.lang = lang;
      this.value = value;
      this.extensions = extensions;
   }

   public java.lang.String getLang()
   {
      return lang;
   }

   public void setLang(java.lang.String lang)
   {
      this.lang = lang;
   }

   public java.lang.String getValue()
   {
      return value;
   }

   public void setValue(java.lang.String value)
   {
      this.value = value;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
