// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class ResourceList implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = -3559596475875197452L;
   protected Resource[] resources;
   protected Extension[] extensions;

   public ResourceList()
   {
   }

   public ResourceList(Resource[] resources, Extension[] extensions)
   {
      this.resources = resources;
      this.extensions = extensions;
   }

   public Resource[] getResources()
   {
      return resources;
   }

   public void setResources(Resource[] resources)
   {
      this.resources = resources;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
