// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class Resource implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = 6572440342306998048L;
   protected java.lang.String resourceName;
   protected ResourceValue[] values;
   protected Extension[] extensions;

   public Resource()
   {
   }

   public Resource(java.lang.String resourceName, ResourceValue[] values, Extension[] extensions)
   {
      this.resourceName = resourceName;
      this.values = values;
      this.extensions = extensions;
   }

   public java.lang.String getResourceName()
   {
      return resourceName;
   }

   public void setResourceName(java.lang.String resourceName)
   {
      this.resourceName = resourceName;
   }

   public ResourceValue[] getValues()
   {
      return values;
   }

   public void setValues(ResourceValue[] values)
   {
      this.values = values;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
