// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class ReturnAny implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = 4214536646012200105L;
   protected Extension[] extensions;

   public ReturnAny()
   {
   }

   public ReturnAny(Extension[] extensions)
   {
      this.extensions = extensions;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
