// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class ServiceDescription implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = -2735707425602275713L;
   protected boolean requiresRegistration;
   protected PortletDescription[] offeredPortlets;
   protected ItemDescription[] userCategoryDescriptions;
   protected ItemDescription[] customUserProfileItemDescriptions;
   protected ItemDescription[] customWindowStateDescriptions;
   protected ItemDescription[] customModeDescriptions;
   protected CookieProtocol requiresInitCookie;
   protected ModelDescription registrationPropertyDescription;
   protected java.lang.String[] locales;
   protected ResourceList resourceList;
   protected Extension[] extensions;

   public ServiceDescription()
   {
   }

   public ServiceDescription(boolean requiresRegistration, PortletDescription[] offeredPortlets, ItemDescription[] userCategoryDescriptions, ItemDescription[] customUserProfileItemDescriptions, ItemDescription[] customWindowStateDescriptions, ItemDescription[] customModeDescriptions, CookieProtocol requiresInitCookie, ModelDescription registrationPropertyDescription, java.lang.String[] locales, ResourceList resourceList, Extension[] extensions)
   {
      this.requiresRegistration = requiresRegistration;
      this.offeredPortlets = offeredPortlets;
      this.userCategoryDescriptions = userCategoryDescriptions;
      this.customUserProfileItemDescriptions = customUserProfileItemDescriptions;
      this.customWindowStateDescriptions = customWindowStateDescriptions;
      this.customModeDescriptions = customModeDescriptions;
      this.requiresInitCookie = requiresInitCookie;
      this.registrationPropertyDescription = registrationPropertyDescription;
      this.locales = locales;
      this.resourceList = resourceList;
      this.extensions = extensions;
   }

   public boolean isRequiresRegistration()
   {
      return requiresRegistration;
   }

   public void setRequiresRegistration(boolean requiresRegistration)
   {
      this.requiresRegistration = requiresRegistration;
   }

   public PortletDescription[] getOfferedPortlets()
   {
      return offeredPortlets;
   }

   public void setOfferedPortlets(PortletDescription[] offeredPortlets)
   {
      this.offeredPortlets = offeredPortlets;
   }

   public ItemDescription[] getUserCategoryDescriptions()
   {
      return userCategoryDescriptions;
   }

   public void setUserCategoryDescriptions(ItemDescription[] userCategoryDescriptions)
   {
      this.userCategoryDescriptions = userCategoryDescriptions;
   }

   public ItemDescription[] getCustomUserProfileItemDescriptions()
   {
      return customUserProfileItemDescriptions;
   }

   public void setCustomUserProfileItemDescriptions(ItemDescription[] customUserProfileItemDescriptions)
   {
      this.customUserProfileItemDescriptions = customUserProfileItemDescriptions;
   }

   public ItemDescription[] getCustomWindowStateDescriptions()
   {
      return customWindowStateDescriptions;
   }

   public void setCustomWindowStateDescriptions(ItemDescription[] customWindowStateDescriptions)
   {
      this.customWindowStateDescriptions = customWindowStateDescriptions;
   }

   public ItemDescription[] getCustomModeDescriptions()
   {
      return customModeDescriptions;
   }

   public void setCustomModeDescriptions(ItemDescription[] customModeDescriptions)
   {
      this.customModeDescriptions = customModeDescriptions;
   }

   public CookieProtocol getRequiresInitCookie()
   {
      return requiresInitCookie;
   }

   public void setRequiresInitCookie(CookieProtocol requiresInitCookie)
   {
      this.requiresInitCookie = requiresInitCookie;
   }

   public ModelDescription getRegistrationPropertyDescription()
   {
      return registrationPropertyDescription;
   }

   public void setRegistrationPropertyDescription(ModelDescription registrationPropertyDescription)
   {
      this.registrationPropertyDescription = registrationPropertyDescription;
   }

   public java.lang.String[] getLocales()
   {
      return locales;
   }

   public void setLocales(java.lang.String[] locales)
   {
      this.locales = locales;
   }

   public ResourceList getResourceList()
   {
      return resourceList;
   }

   public void setResourceList(ResourceList resourceList)
   {
      this.resourceList = resourceList;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
