// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class SetPortletProperties implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = -8493574174140633553L;
   protected RegistrationContext registrationContext;
   protected PortletContext portletContext;
   protected UserContext userContext;
   protected PropertyList propertyList;

   public SetPortletProperties()
   {
   }

   public SetPortletProperties(RegistrationContext registrationContext, PortletContext portletContext, UserContext userContext, PropertyList propertyList)
   {
      this.registrationContext = registrationContext;
      this.portletContext = portletContext;
      this.userContext = userContext;
      this.propertyList = propertyList;
   }

   public RegistrationContext getRegistrationContext()
   {
      return registrationContext;
   }

   public void setRegistrationContext(RegistrationContext registrationContext)
   {
      this.registrationContext = registrationContext;
   }

   public PortletContext getPortletContext()
   {
      return portletContext;
   }

   public void setPortletContext(PortletContext portletContext)
   {
      this.portletContext = portletContext;
   }

   public UserContext getUserContext()
   {
      return userContext;
   }

   public void setUserContext(UserContext userContext)
   {
      this.userContext = userContext;
   }

   public PropertyList getPropertyList()
   {
      return propertyList;
   }

   public void setPropertyList(PropertyList propertyList)
   {
      this.propertyList = propertyList;
   }
}
