// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class TelephoneNum implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = 2797048226121530111L;
   protected java.lang.String intcode;
   protected java.lang.String loccode;
   protected java.lang.String number;
   protected java.lang.String ext;
   protected java.lang.String comment;
   protected Extension[] extensions;

   public TelephoneNum()
   {
   }

   public TelephoneNum(java.lang.String intcode, java.lang.String loccode, java.lang.String number, java.lang.String ext, java.lang.String comment, Extension[] extensions)
   {
      this.intcode = intcode;
      this.loccode = loccode;
      this.number = number;
      this.ext = ext;
      this.comment = comment;
      this.extensions = extensions;
   }

   public java.lang.String getIntcode()
   {
      return intcode;
   }

   public void setIntcode(java.lang.String intcode)
   {
      this.intcode = intcode;
   }

   public java.lang.String getLoccode()
   {
      return loccode;
   }

   public void setLoccode(java.lang.String loccode)
   {
      this.loccode = loccode;
   }

   public java.lang.String getNumber()
   {
      return number;
   }

   public void setNumber(java.lang.String number)
   {
      this.number = number;
   }

   public java.lang.String getExt()
   {
      return ext;
   }

   public void setExt(java.lang.String ext)
   {
      this.ext = ext;
   }

   public java.lang.String getComment()
   {
      return comment;
   }

   public void setComment(java.lang.String comment)
   {
      this.comment = comment;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
