// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class Telecom implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = 1432675148383103561L;
   protected TelephoneNum telephone;
   protected TelephoneNum fax;
   protected TelephoneNum mobile;
   protected TelephoneNum pager;
   protected Extension[] extensions;

   public Telecom()
   {
   }

   public Telecom(TelephoneNum telephone, TelephoneNum fax, TelephoneNum mobile, TelephoneNum pager, Extension[] extensions)
   {
      this.telephone = telephone;
      this.fax = fax;
      this.mobile = mobile;
      this.pager = pager;
      this.extensions = extensions;
   }

   public TelephoneNum getTelephone()
   {
      return telephone;
   }

   public void setTelephone(TelephoneNum telephone)
   {
      this.telephone = telephone;
   }

   public TelephoneNum getFax()
   {
      return fax;
   }

   public void setFax(TelephoneNum fax)
   {
      this.fax = fax;
   }

   public TelephoneNum getMobile()
   {
      return mobile;
   }

   public void setMobile(TelephoneNum mobile)
   {
      this.mobile = mobile;
   }

   public TelephoneNum getPager()
   {
      return pager;
   }

   public void setPager(TelephoneNum pager)
   {
      this.pager = pager;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
