// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class Templates implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = -7321632876065387006L;
   protected java.lang.String defaultTemplate;
   protected java.lang.String blockingActionTemplate;
   protected java.lang.String renderTemplate;
   protected java.lang.String resourceTemplate;
   protected java.lang.String secureDefaultTemplate;
   protected java.lang.String secureBlockingActionTemplate;
   protected java.lang.String secureRenderTemplate;
   protected java.lang.String secureResourceTemplate;
   protected Extension[] extensions;

   public Templates()
   {
   }

   public Templates(java.lang.String defaultTemplate, java.lang.String blockingActionTemplate, java.lang.String renderTemplate, java.lang.String resourceTemplate, java.lang.String secureDefaultTemplate, java.lang.String secureBlockingActionTemplate, java.lang.String secureRenderTemplate, java.lang.String secureResourceTemplate, Extension[] extensions)
   {
      this.defaultTemplate = defaultTemplate;
      this.blockingActionTemplate = blockingActionTemplate;
      this.renderTemplate = renderTemplate;
      this.resourceTemplate = resourceTemplate;
      this.secureDefaultTemplate = secureDefaultTemplate;
      this.secureBlockingActionTemplate = secureBlockingActionTemplate;
      this.secureRenderTemplate = secureRenderTemplate;
      this.secureResourceTemplate = secureResourceTemplate;
      this.extensions = extensions;
   }

   public java.lang.String getDefaultTemplate()
   {
      return defaultTemplate;
   }

   public void setDefaultTemplate(java.lang.String defaultTemplate)
   {
      this.defaultTemplate = defaultTemplate;
   }

   public java.lang.String getBlockingActionTemplate()
   {
      return blockingActionTemplate;
   }

   public void setBlockingActionTemplate(java.lang.String blockingActionTemplate)
   {
      this.blockingActionTemplate = blockingActionTemplate;
   }

   public java.lang.String getRenderTemplate()
   {
      return renderTemplate;
   }

   public void setRenderTemplate(java.lang.String renderTemplate)
   {
      this.renderTemplate = renderTemplate;
   }

   public java.lang.String getResourceTemplate()
   {
      return resourceTemplate;
   }

   public void setResourceTemplate(java.lang.String resourceTemplate)
   {
      this.resourceTemplate = resourceTemplate;
   }

   public java.lang.String getSecureDefaultTemplate()
   {
      return secureDefaultTemplate;
   }

   public void setSecureDefaultTemplate(java.lang.String secureDefaultTemplate)
   {
      this.secureDefaultTemplate = secureDefaultTemplate;
   }

   public java.lang.String getSecureBlockingActionTemplate()
   {
      return secureBlockingActionTemplate;
   }

   public void setSecureBlockingActionTemplate(java.lang.String secureBlockingActionTemplate)
   {
      this.secureBlockingActionTemplate = secureBlockingActionTemplate;
   }

   public java.lang.String getSecureRenderTemplate()
   {
      return secureRenderTemplate;
   }

   public void setSecureRenderTemplate(java.lang.String secureRenderTemplate)
   {
      this.secureRenderTemplate = secureRenderTemplate;
   }

   public java.lang.String getSecureResourceTemplate()
   {
      return secureResourceTemplate;
   }

   public void setSecureResourceTemplate(java.lang.String secureResourceTemplate)
   {
      this.secureResourceTemplate = secureResourceTemplate;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
