// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;


public class UnsupportedMimeTypeFault extends Fault
{ 
   /** The serialVersionUID */
   private static final long serialVersionUID = -5974154578151021407L;

   public UnsupportedMimeTypeFault()
   {
   } 
}
