// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core; 

public class UnsupportedLocaleFault extends Fault
{ 
   /** The serialVersionUID */
   private static final long serialVersionUID = -8787117782967550334L;

   public UnsupportedLocaleFault()
   {
   } 
}
