// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class UpdateResponse implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = -3007501145027671717L;
   protected SessionContext sessionContext;
   protected PortletContext portletContext;
   protected MarkupContext markupContext;
   protected java.lang.String navigationalState;
   protected java.lang.String newWindowState;
   protected java.lang.String newMode;

   public UpdateResponse()
   {
   }

   public UpdateResponse(SessionContext sessionContext, PortletContext portletContext, MarkupContext markupContext, java.lang.String navigationalState, java.lang.String newWindowState, java.lang.String newMode)
   {
      this.sessionContext = sessionContext;
      this.portletContext = portletContext;
      this.markupContext = markupContext;
      this.navigationalState = navigationalState;
      this.newWindowState = newWindowState;
      this.newMode = newMode;
   }

   public SessionContext getSessionContext()
   {
      return sessionContext;
   }

   public void setSessionContext(SessionContext sessionContext)
   {
      this.sessionContext = sessionContext;
   }

   public PortletContext getPortletContext()
   {
      return portletContext;
   }

   public void setPortletContext(PortletContext portletContext)
   {
      this.portletContext = portletContext;
   }

   public MarkupContext getMarkupContext()
   {
      return markupContext;
   }

   public void setMarkupContext(MarkupContext markupContext)
   {
      this.markupContext = markupContext;
   }

   public java.lang.String getNavigationalState()
   {
      return navigationalState;
   }

   public void setNavigationalState(java.lang.String navigationalState)
   {
      this.navigationalState = navigationalState;
   }

   public java.lang.String getNewWindowState()
   {
      return newWindowState;
   }

   public void setNewWindowState(java.lang.String newWindowState)
   {
      this.newWindowState = newWindowState;
   }

   public java.lang.String getNewMode()
   {
      return newMode;
   }

   public void setNewMode(java.lang.String newMode)
   {
      this.newMode = newMode;
   }
}
