// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class UploadContext implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = 3248758252239905413L;
   protected java.lang.String mimeType;
   protected byte[] uploadData;
   protected NamedString[] mimeAttributes;
   protected Extension[] extensions;

   public UploadContext()
   {
   }

   public UploadContext(java.lang.String mimeType, byte[] uploadData, NamedString[] mimeAttributes, Extension[] extensions)
   {
      this.mimeType = mimeType;
      this.uploadData = uploadData;
      this.mimeAttributes = mimeAttributes;
      this.extensions = extensions;
   }

   public java.lang.String getMimeType()
   {
      return mimeType;
   }

   public void setMimeType(java.lang.String mimeType)
   {
      this.mimeType = mimeType;
   }

   public byte[] getUploadData()
   {
      return uploadData;
   }

   public void setUploadData(byte[] uploadData)
   {
      this.uploadData = uploadData;
   }

   public NamedString[] getMimeAttributes()
   {
      return mimeAttributes;
   }

   public void setMimeAttributes(NamedString[] mimeAttributes)
   {
      this.mimeAttributes = mimeAttributes;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
