// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.wsrp.core;

import java.io.Serializable;


public class UserProfile implements Serializable
{
   /** The serialVersionUID */
   private static final long serialVersionUID = 4411633222034360258L;
   protected PersonName name;
   protected java.util.Calendar bdate;
   protected java.lang.String gender;
   protected EmployerInfo employerInfo;
   protected Contact homeInfo;
   protected Contact businessInfo;
   protected Extension[] extensions;

   public UserProfile()
   {
   }

   public UserProfile(PersonName name, java.util.Calendar bdate, java.lang.String gender, EmployerInfo employerInfo, Contact homeInfo, Contact businessInfo, Extension[] extensions)
   {
      this.name = name;
      this.bdate = bdate;
      this.gender = gender;
      this.employerInfo = employerInfo;
      this.homeInfo = homeInfo;
      this.businessInfo = businessInfo;
      this.extensions = extensions;
   }

   public PersonName getName()
   {
      return name;
   }

   public void setName(PersonName name)
   {
      this.name = name;
   }

   public java.util.Calendar getBdate()
   {
      return bdate;
   }

   public void setBdate(java.util.Calendar bdate)
   {
      this.bdate = bdate;
   }

   public java.lang.String getGender()
   {
      return gender;
   }

   public void setGender(java.lang.String gender)
   {
      this.gender = gender;
   }

   public EmployerInfo getEmployerInfo()
   {
      return employerInfo;
   }

   public void setEmployerInfo(EmployerInfo employerInfo)
   {
      this.employerInfo = employerInfo;
   }

   public Contact getHomeInfo()
   {
      return homeInfo;
   }

   public void setHomeInfo(Contact homeInfo)
   {
      this.homeInfo = homeInfo;
   }

   public Contact getBusinessInfo()
   {
      return businessInfo;
   }

   public void setBusinessInfo(Contact businessInfo)
   {
      this.businessInfo = businessInfo;
   }

   public Extension[] getExtensions()
   {
      return extensions;
   }

   public void setExtensions(Extension[] extensions)
   {
      this.extensions = extensions;
   }
}
