// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.jboss.test.webservice.marshalltest._arrays;


public class BooleanArray {
    private boolean[] value;
    
    public BooleanArray() {
    }
    
    public BooleanArray(boolean[] sourceArray) {
        value = sourceArray;
    }
    
    public void fromArray(boolean[] sourceArray) {
        this.value = sourceArray;
    }
    
    public boolean[] toArray() {
        return value;
    }
    
    public boolean[] getValue() {
        return value;
    }
    
    public void setValue(boolean[] value) {
        this.value = value;
    }
}
