// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.jboss.test.webservice.marshalltest._arrays;


public class DoubleArray {
    private double[] value;
    
    public DoubleArray() {
    }
    
    public DoubleArray(double[] sourceArray) {
        value = sourceArray;
    }
    
    public void fromArray(double[] sourceArray) {
        this.value = sourceArray;
    }
    
    public double[] toArray() {
        return value;
    }
    
    public double[] getValue() {
        return value;
    }
    
    public void setValue(double[] value) {
        this.value = value;
    }
}
