// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.jboss.test.webservice.marshalltest._arrays;


public class FloatArray {
    private float[] value;
    
    public FloatArray() {
    }
    
    public FloatArray(float[] sourceArray) {
        value = sourceArray;
    }
    
    public void fromArray(float[] sourceArray) {
        this.value = sourceArray;
    }
    
    public float[] toArray() {
        return value;
    }
    
    public float[] getValue() {
        return value;
    }
    
    public void setValue(float[] value) {
        this.value = value;
    }
}
