// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.jboss.test.webservice.marshalltest._arrays;


public class IntArray {
    private int[] value;
    
    public IntArray() {
    }
    
    public IntArray(int[] sourceArray) {
        value = sourceArray;
    }
    
    public void fromArray(int[] sourceArray) {
        this.value = sourceArray;
    }
    
    public int[] toArray() {
        return value;
    }
    
    public int[] getValue() {
        return value;
    }
    
    public void setValue(int[] value) {
        this.value = value;
    }
}
