// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.jboss.test.webservice.marshalltest._arrays;


public class LongArray {
    private long[] value;
    
    public LongArray() {
    }
    
    public LongArray(long[] sourceArray) {
        value = sourceArray;
    }
    
    public void fromArray(long[] sourceArray) {
        this.value = sourceArray;
    }
    
    public long[] toArray() {
        return value;
    }
    
    public long[] getValue() {
        return value;
    }
    
    public void setValue(long[] value) {
        this.value = value;
    }
}
