// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.jboss.test.webservice.marshalltest._arrays;


public class ShortArray {
    private short[] value;
    
    public ShortArray() {
    }
    
    public ShortArray(short[] sourceArray) {
        value = sourceArray;
    }
    
    public void fromArray(short[] sourceArray) {
        this.value = sourceArray;
    }
    
    public short[] toArray() {
        return value;
    }
    
    public short[] getValue() {
        return value;
    }
    
    public void setValue(short[] value) {
        this.value = value;
    }
}
