// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws632._arrays.java.lang;


public class StringArrayArray {
    private org.jboss.test.webservice.jbws632._arrays.java.lang.StringArray[] myStringArray;
    
    public StringArrayArray() {
    }
    
    public StringArrayArray(org.jboss.test.webservice.jbws632._arrays.java.lang.StringArray[] sourceArray) {
        myStringArray = sourceArray;
    }
    
    public StringArrayArray(java.lang.String[][] sourceArray) {
        fromArray(sourceArray);
    }
    
    public void fromArray(java.lang.String[][] sourceArray) {
        myStringArray = new org.jboss.test.webservice.jbws632._arrays.java.lang.StringArray[sourceArray.length];
        for (int i=0; i<sourceArray.length; i++) {
            myStringArray[i] = new org.jboss.test.webservice.jbws632._arrays.java.lang.StringArray(sourceArray[i]);
        }
    }
    
    public java.lang.String[][] toArray() {
        java.lang.String[][] tmpArray = new java.lang.String[myStringArray.length][];
        for (int i=0; i<myStringArray.length; i++) {
            tmpArray[i] = myStringArray[i].toArray();
        }
        return tmpArray;
    }
    
    public org.jboss.test.webservice.jbws632._arrays.java.lang.StringArray[] getValue() {
        return myStringArray;
    }
    
    public void setValue(org.jboss.test.webservice.jbws632._arrays.java.lang.StringArray[] myStringArray) {
        this.myStringArray = myStringArray;
    }
}
