// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.jboss.test.webservice.jbws626._arrays.org.jboss.test.webservice.jbws626;


public class ValueObjArray {
    private org.jboss.test.webservice.jbws626.ValueObj[] value;
    
    public ValueObjArray() {
    }
    
    public ValueObjArray(org.jboss.test.webservice.jbws626.ValueObj[] sourceArray) {
        value = sourceArray;
    }
    
    public void fromArray(org.jboss.test.webservice.jbws626.ValueObj[] sourceArray) {
        this.value = sourceArray;
    }
    
    public org.jboss.test.webservice.jbws626.ValueObj[] toArray() {
        return value;
    }
    
    public org.jboss.test.webservice.jbws626.ValueObj[] getValue() {
        return value;
    }
    
    public void setValue(org.jboss.test.webservice.jbws626.ValueObj[] value) {
        this.value = value;
    }
}
