// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws663;


public class ArrayOfCarrier {
    protected org.jboss.test.webservice.jbws663.Carrier[] carrier;
    
    public ArrayOfCarrier() {
    }
    
    public ArrayOfCarrier(org.jboss.test.webservice.jbws663.Carrier[] carrier) {
        this.carrier = carrier;
    }
    
    public org.jboss.test.webservice.jbws663.Carrier[] getCarrier() {
        return carrier;
    }
    
    public void setCarrier(org.jboss.test.webservice.jbws663.Carrier[] carrier) {
        this.carrier = carrier;
    }
}
