// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws663;


public class ArrayOfCountryCode {
    protected org.jboss.test.webservice.jbws663.CountryCode[] countryCode;
    
    public ArrayOfCountryCode() {
    }
    
    public ArrayOfCountryCode(org.jboss.test.webservice.jbws663.CountryCode[] countryCode) {
        this.countryCode = countryCode;
    }
    
    public org.jboss.test.webservice.jbws663.CountryCode[] getCountryCode() {
        return countryCode;
    }
    
    public void setCountryCode(org.jboss.test.webservice.jbws663.CountryCode[] countryCode) {
        this.countryCode = countryCode;
    }
}
