// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws663;


public class ArrayOfSMSTextMessageTargetStatus {
    protected org.jboss.test.webservice.jbws663.SMSTextMessageTargetStatus[] SMSTextMessageTargetStatus;
    
    public ArrayOfSMSTextMessageTargetStatus() {
    }
    
    public ArrayOfSMSTextMessageTargetStatus(org.jboss.test.webservice.jbws663.SMSTextMessageTargetStatus[] SMSTextMessageTargetStatus) {
        this.SMSTextMessageTargetStatus = SMSTextMessageTargetStatus;
    }
    
    public org.jboss.test.webservice.jbws663.SMSTextMessageTargetStatus[] getSMSTextMessageTargetStatus() {
        return SMSTextMessageTargetStatus;
    }
    
    public void setSMSTextMessageTargetStatus(org.jboss.test.webservice.jbws663.SMSTextMessageTargetStatus[] SMSTextMessageTargetStatus) {
        this.SMSTextMessageTargetStatus = SMSTextMessageTargetStatus;
    }
}
