// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws663;


public class Carrier {
    protected int carrierID;
    protected java.lang.String carrierName;
    protected java.lang.String country;
    protected int maxTextLength;
    protected java.lang.String networkStandard;
    
    public Carrier() {
    }
    
    public Carrier(int carrierID, java.lang.String carrierName, java.lang.String country, int maxTextLength, java.lang.String networkStandard) {
        this.carrierID = carrierID;
        this.carrierName = carrierName;
        this.country = country;
        this.maxTextLength = maxTextLength;
        this.networkStandard = networkStandard;
    }
    
    public int getCarrierID() {
        return carrierID;
    }
    
    public void setCarrierID(int carrierID) {
        this.carrierID = carrierID;
    }
    
    public java.lang.String getCarrierName() {
        return carrierName;
    }
    
    public void setCarrierName(java.lang.String carrierName) {
        this.carrierName = carrierName;
    }
    
    public java.lang.String getCountry() {
        return country;
    }
    
    public void setCountry(java.lang.String country) {
        this.country = country;
    }
    
    public int getMaxTextLength() {
        return maxTextLength;
    }
    
    public void setMaxTextLength(int maxTextLength) {
        this.maxTextLength = maxTextLength;
    }
    
    public java.lang.String getNetworkStandard() {
        return networkStandard;
    }
    
    public void setNetworkStandard(java.lang.String networkStandard) {
        this.networkStandard = networkStandard;
    }
}
