// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws663;


public class CountryCode {
    protected java.lang.String country;
    protected java.lang.String code;
    
    public CountryCode() {
    }
    
    public CountryCode(java.lang.String country, java.lang.String code) {
        this.country = country;
        this.code = code;
    }
    
    public java.lang.String getCountry() {
        return country;
    }
    
    public void setCountry(java.lang.String country) {
        this.country = country;
    }
    
    public java.lang.String getCode() {
        return code;
    }
    
    public void setCode(java.lang.String code) {
        this.code = code;
    }
}
