// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws663;


public class GetCountryCodesResponse {
    protected org.jboss.test.webservice.jbws663.ArrayOfCountryCode getCountryCodesResult;
    
    public GetCountryCodesResponse() {
    }
    
    public GetCountryCodesResponse(org.jboss.test.webservice.jbws663.ArrayOfCountryCode getCountryCodesResult) {
        this.getCountryCodesResult = getCountryCodesResult;
    }
    
    public org.jboss.test.webservice.jbws663.ArrayOfCountryCode getGetCountryCodesResult() {
        return getCountryCodesResult;
    }
    
    public void setGetCountryCodesResult(org.jboss.test.webservice.jbws663.ArrayOfCountryCode getCountryCodesResult) {
        this.getCountryCodesResult = getCountryCodesResult;
    }
}
