// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws663;


public class GetSupportedCarriersResponse {
    protected org.jboss.test.webservice.jbws663.ArrayOfCarrier getSupportedCarriersResult;
    
    public GetSupportedCarriersResponse() {
    }
    
    public GetSupportedCarriersResponse(org.jboss.test.webservice.jbws663.ArrayOfCarrier getSupportedCarriersResult) {
        this.getSupportedCarriersResult = getSupportedCarriersResult;
    }
    
    public org.jboss.test.webservice.jbws663.ArrayOfCarrier getGetSupportedCarriersResult() {
        return getSupportedCarriersResult;
    }
    
    public void setGetSupportedCarriersResult(org.jboss.test.webservice.jbws663.ArrayOfCarrier getSupportedCarriersResult) {
        this.getSupportedCarriersResult = getSupportedCarriersResult;
    }
}
