// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws663;


public class LicenseInfo {
    protected org.jboss.test.webservice.jbws663.UnregisteredUser unregisteredUser;
    protected org.jboss.test.webservice.jbws663.RegisteredUser registeredUser;
    
    public LicenseInfo() {
    }
    
    public LicenseInfo(org.jboss.test.webservice.jbws663.UnregisteredUser unregisteredUser, org.jboss.test.webservice.jbws663.RegisteredUser registeredUser) {
        this.unregisteredUser = unregisteredUser;
        this.registeredUser = registeredUser;
    }
    
    public org.jboss.test.webservice.jbws663.UnregisteredUser getUnregisteredUser() {
        return unregisteredUser;
    }
    
    public void setUnregisteredUser(org.jboss.test.webservice.jbws663.UnregisteredUser unregisteredUser) {
        this.unregisteredUser = unregisteredUser;
    }
    
    public org.jboss.test.webservice.jbws663.RegisteredUser getRegisteredUser() {
        return registeredUser;
    }
    
    public void setRegisteredUser(org.jboss.test.webservice.jbws663.RegisteredUser registeredUser) {
        this.registeredUser = registeredUser;
    }
}
