// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws663;


public class RegisteredUser {
    protected java.lang.String userID;
    protected java.lang.String password;
    
    public RegisteredUser() {
    }
    
    public RegisteredUser(java.lang.String userID, java.lang.String password) {
        this.userID = userID;
        this.password = password;
    }
    
    public java.lang.String getUserID() {
        return userID;
    }
    
    public void setUserID(java.lang.String userID) {
        this.userID = userID;
    }
    
    public java.lang.String getPassword() {
        return password;
    }
    
    public void setPassword(java.lang.String password) {
        this.password = password;
    }
}
