// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws663;


public class ResponseInfo {
    protected int responseCode;
    protected java.lang.String response;
    
    public ResponseInfo() {
    }
    
    public ResponseInfo(int responseCode, java.lang.String response) {
        this.responseCode = responseCode;
        this.response = response;
    }
    
    public int getResponseCode() {
        return responseCode;
    }
    
    public void setResponseCode(int responseCode) {
        this.responseCode = responseCode;
    }
    
    public java.lang.String getResponse() {
        return response;
    }
    
    public void setResponse(java.lang.String response) {
        this.response = response;
    }
}
