// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws663;


public class SendMessagesBulkResponse {
    protected org.jboss.test.webservice.jbws663.ArrayOfSMSTextMessageTargetStatus sendMessagesBulkResult;
    
    public SendMessagesBulkResponse() {
    }
    
    public SendMessagesBulkResponse(org.jboss.test.webservice.jbws663.ArrayOfSMSTextMessageTargetStatus sendMessagesBulkResult) {
        this.sendMessagesBulkResult = sendMessagesBulkResult;
    }
    
    public org.jboss.test.webservice.jbws663.ArrayOfSMSTextMessageTargetStatus getSendMessagesBulkResult() {
        return sendMessagesBulkResult;
    }
    
    public void setSendMessagesBulkResult(org.jboss.test.webservice.jbws663.ArrayOfSMSTextMessageTargetStatus sendMessagesBulkResult) {
        this.sendMessagesBulkResult = sendMessagesBulkResult;
    }
}
