// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws663;


public class SendMessageResponse {
    protected org.jboss.test.webservice.jbws663.SMSTextMessageTargetStatus sendMessageResult;
    
    public SendMessageResponse() {
    }
    
    public SendMessageResponse(org.jboss.test.webservice.jbws663.SMSTextMessageTargetStatus sendMessageResult) {
        this.sendMessageResult = sendMessageResult;
    }
    
    public org.jboss.test.webservice.jbws663.SMSTextMessageTargetStatus getSendMessageResult() {
        return sendMessageResult;
    }
    
    public void setSendMessageResult(org.jboss.test.webservice.jbws663.SMSTextMessageTargetStatus sendMessageResult) {
        this.sendMessageResult = sendMessageResult;
    }
}
