// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws663;


public class SendMessagesBulk {
    protected org.jboss.test.webservice.jbws663.ArrayOfString toNumbers;
    protected java.lang.String fromNumber;
    protected java.lang.String fromName;
    protected java.lang.String messageText;
    
    public SendMessagesBulk() {
    }
    
    public SendMessagesBulk(org.jboss.test.webservice.jbws663.ArrayOfString toNumbers, java.lang.String fromNumber, java.lang.String fromName, java.lang.String messageText) {
        this.toNumbers = toNumbers;
        this.fromNumber = fromNumber;
        this.fromName = fromName;
        this.messageText = messageText;
    }
    
    public org.jboss.test.webservice.jbws663.ArrayOfString getToNumbers() {
        return toNumbers;
    }
    
    public void setToNumbers(org.jboss.test.webservice.jbws663.ArrayOfString toNumbers) {
        this.toNumbers = toNumbers;
    }
    
    public java.lang.String getFromNumber() {
        return fromNumber;
    }
    
    public void setFromNumber(java.lang.String fromNumber) {
        this.fromNumber = fromNumber;
    }
    
    public java.lang.String getFromName() {
        return fromName;
    }
    
    public void setFromName(java.lang.String fromName) {
        this.fromName = fromName;
    }
    
    public java.lang.String getMessageText() {
        return messageText;
    }
    
    public void setMessageText(java.lang.String messageText) {
        this.messageText = messageText;
    }
}
