// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws663;


public class SMSTextMessageTargetStatus {
    protected java.lang.String toNumber;
    protected java.lang.String trackingTag;
    protected org.jboss.test.webservice.jbws663.MessageStatus messageStatus;
    
    public SMSTextMessageTargetStatus() {
    }
    
    public SMSTextMessageTargetStatus(java.lang.String toNumber, java.lang.String trackingTag, org.jboss.test.webservice.jbws663.MessageStatus messageStatus) {
        this.toNumber = toNumber;
        this.trackingTag = trackingTag;
        this.messageStatus = messageStatus;
    }
    
    public java.lang.String getToNumber() {
        return toNumber;
    }
    
    public void setToNumber(java.lang.String toNumber) {
        this.toNumber = toNumber;
    }
    
    public java.lang.String getTrackingTag() {
        return trackingTag;
    }
    
    public void setTrackingTag(java.lang.String trackingTag) {
        this.trackingTag = trackingTag;
    }
    
    public org.jboss.test.webservice.jbws663.MessageStatus getMessageStatus() {
        return messageStatus;
    }
    
    public void setMessageStatus(org.jboss.test.webservice.jbws663.MessageStatus messageStatus) {
        this.messageStatus = messageStatus;
    }
}
