// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws663;

public interface SMSTextMessagingSoapBare extends java.rmi.Remote {
    public org.jboss.test.webservice.jbws663.SendMessageResponse sendMessage(org.jboss.test.webservice.jbws663.SendMessage parameters) throws 
         java.rmi.RemoteException;
    public org.jboss.test.webservice.jbws663.SendMessagesBulkResponse sendMessagesBulk(org.jboss.test.webservice.jbws663.SendMessagesBulk parameters) throws 
         java.rmi.RemoteException;
    public org.jboss.test.webservice.jbws663.TrackMessageResponse trackMessage(org.jboss.test.webservice.jbws663.TrackMessage parameters) throws 
         java.rmi.RemoteException;
    public org.jboss.test.webservice.jbws663.TrackMessagesBulkResponse trackMessagesBulk(org.jboss.test.webservice.jbws663.TrackMessagesBulk parameters) throws 
         java.rmi.RemoteException;
    public org.jboss.test.webservice.jbws663.GetSupportedCarriersResponse getSupportedCarriers(org.jboss.test.webservice.jbws663.GetSupportedCarriers parameters) throws 
         java.rmi.RemoteException;
    public org.jboss.test.webservice.jbws663.GetCountryCodesResponse getCountryCodes(org.jboss.test.webservice.jbws663.GetCountryCodes parameters) throws 
         java.rmi.RemoteException;
    public org.jboss.test.webservice.jbws663.GetRemainingHitsResponse getRemainingHits(org.jboss.test.webservice.jbws663.GetRemainingHits parameters) throws 
         java.rmi.RemoteException;
}
