// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws663;

public interface SMSTextMessagingSoapWrapped extends java.rmi.Remote {
    public org.jboss.test.webservice.jbws663.SMSTextMessageTargetStatus sendMessage(java.lang.String toNumber, java.lang.String fromNumber, java.lang.String fromName, java.lang.String messageText) throws 
         java.rmi.RemoteException;
    public org.jboss.test.webservice.jbws663.ArrayOfSMSTextMessageTargetStatus sendMessagesBulk(org.jboss.test.webservice.jbws663.ArrayOfString toNumbers, java.lang.String fromNumber, java.lang.String fromName, java.lang.String messageText) throws 
         java.rmi.RemoteException;
    public org.jboss.test.webservice.jbws663.SMSTextMessageTargetStatus trackMessage(java.lang.String trackingTag) throws 
         java.rmi.RemoteException;
    public org.jboss.test.webservice.jbws663.ArrayOfSMSTextMessageTargetStatus trackMessagesBulk(org.jboss.test.webservice.jbws663.ArrayOfString trackingTags) throws 
         java.rmi.RemoteException;
    public org.jboss.test.webservice.jbws663.ArrayOfCarrier getSupportedCarriers() throws 
         java.rmi.RemoteException;
    public org.jboss.test.webservice.jbws663.ArrayOfCountryCode getCountryCodes() throws 
         java.rmi.RemoteException;
    public org.jboss.test.webservice.jbws663.GetRemainingHitsResponse getRemainingHits() throws 
         java.rmi.RemoteException;
}
