// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws663;


public class TrackMessagesBulk {
    protected org.jboss.test.webservice.jbws663.ArrayOfString trackingTags;
    
    public TrackMessagesBulk() {
    }
    
    public TrackMessagesBulk(org.jboss.test.webservice.jbws663.ArrayOfString trackingTags) {
        this.trackingTags = trackingTags;
    }
    
    public org.jboss.test.webservice.jbws663.ArrayOfString getTrackingTags() {
        return trackingTags;
    }
    
    public void setTrackingTags(org.jboss.test.webservice.jbws663.ArrayOfString trackingTags) {
        this.trackingTags = trackingTags;
    }
}
