// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws663;


public class TrackMessagesBulkResponse {
    protected org.jboss.test.webservice.jbws663.ArrayOfSMSTextMessageTargetStatus trackMessagesBulkResult;
    
    public TrackMessagesBulkResponse() {
    }
    
    public TrackMessagesBulkResponse(org.jboss.test.webservice.jbws663.ArrayOfSMSTextMessageTargetStatus trackMessagesBulkResult) {
        this.trackMessagesBulkResult = trackMessagesBulkResult;
    }
    
    public org.jboss.test.webservice.jbws663.ArrayOfSMSTextMessageTargetStatus getTrackMessagesBulkResult() {
        return trackMessagesBulkResult;
    }
    
    public void setTrackMessagesBulkResult(org.jboss.test.webservice.jbws663.ArrayOfSMSTextMessageTargetStatus trackMessagesBulkResult) {
        this.trackMessagesBulkResult = trackMessagesBulkResult;
    }
}
