// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws663;


public class TrackMessage {
    protected java.lang.String trackingTag;
    
    public TrackMessage() {
    }
    
    public TrackMessage(java.lang.String trackingTag) {
        this.trackingTag = trackingTag;
    }
    
    public java.lang.String getTrackingTag() {
        return trackingTag;
    }
    
    public void setTrackingTag(java.lang.String trackingTag) {
        this.trackingTag = trackingTag;
    }
}
