// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws663;


public class TrackMessageResponse {
    protected org.jboss.test.webservice.jbws663.SMSTextMessageTargetStatus trackMessageResult;
    
    public TrackMessageResponse() {
    }
    
    public TrackMessageResponse(org.jboss.test.webservice.jbws663.SMSTextMessageTargetStatus trackMessageResult) {
        this.trackMessageResult = trackMessageResult;
    }
    
    public org.jboss.test.webservice.jbws663.SMSTextMessageTargetStatus getTrackMessageResult() {
        return trackMessageResult;
    }
    
    public void setTrackMessageResult(org.jboss.test.webservice.jbws663.SMSTextMessageTargetStatus trackMessageResult) {
        this.trackMessageResult = trackMessageResult;
    }
}
