// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws663;


public class UnregisteredUser {
    protected java.lang.String emailAddress;
    
    public UnregisteredUser() {
    }
    
    public UnregisteredUser(java.lang.String emailAddress) {
        this.emailAddress = emailAddress;
    }
    
    public java.lang.String getEmailAddress() {
        return emailAddress;
    }
    
    public void setEmailAddress(java.lang.String emailAddress) {
        this.emailAddress = emailAddress;
    }
}
