// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws484;


public class TestMethodResponse {
    protected int result;
    
    public TestMethodResponse() {
    }
    
    public TestMethodResponse(int result) {
        this.result = result;
    }
    
    public int getResult() {
        return result;
    }
    
    public void setResult(int result) {
        this.result = result;
    }
}
