// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws484;

public interface TestService_PortType extends java.rmi.Remote {
    public int testMethod(java.lang.String aFirstParam, java.lang.String secondParam) throws 
         java.rmi.RemoteException;
}
