// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws484;


public class TestMethod {
    protected java.lang.String aFirstParam;
    protected java.lang.String secondParam;
    
    public TestMethod() {
    }
    
    public TestMethod(java.lang.String aFirstParam, java.lang.String secondParam) {
        this.aFirstParam = aFirstParam;
        this.secondParam = secondParam;
    }
    
    public java.lang.String getAFirstParam() {
        return aFirstParam;
    }
    
    public void setAFirstParam(java.lang.String aFirstParam) {
        this.aFirstParam = aFirstParam;
    }
    
    public java.lang.String getSecondParam() {
        return secondParam;
    }
    
    public void setSecondParam(java.lang.String secondParam) {
        this.secondParam = secondParam;
    }
}
