// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws637;


public class CheckTextBodyResponse {
    protected org.jboss.test.webservice.jbws637.DocumentSummary documentSummary;
    
    public CheckTextBodyResponse() {
    }
    
    public CheckTextBodyResponse(org.jboss.test.webservice.jbws637.DocumentSummary documentSummary) {
        this.documentSummary = documentSummary;
    }
    
    public org.jboss.test.webservice.jbws637.DocumentSummary getDocumentSummary() {
        return documentSummary;
    }
    
    public void setDocumentSummary(org.jboss.test.webservice.jbws637.DocumentSummary documentSummary) {
        this.documentSummary = documentSummary;
    }
}
