// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws637;

public interface CheckSoap extends java.rmi.Remote {
    public org.jboss.test.webservice.jbws637.DocumentSummary checkTextBody(java.lang.String bodyText, java.lang.String licenseKey) throws 
         java.rmi.RemoteException;
    public java.lang.String suggestWord(java.lang.String word) throws 
         java.rmi.RemoteException;
}
