// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws637;


public class CheckTextBody {
    protected java.lang.String bodyText;
    protected java.lang.String licenseKey;
    
    public CheckTextBody() {
    }
    
    public CheckTextBody(java.lang.String bodyText, java.lang.String licenseKey) {
        this.bodyText = bodyText;
        this.licenseKey = licenseKey;
    }
    
    public java.lang.String getBodyText() {
        return bodyText;
    }
    
    public void setBodyText(java.lang.String bodyText) {
        this.bodyText = bodyText;
    }
    
    public java.lang.String getLicenseKey() {
        return licenseKey;
    }
    
    public void setLicenseKey(java.lang.String licenseKey) {
        this.licenseKey = licenseKey;
    }
}
