// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws637;


public class SuggestWord {
    protected java.lang.String word;
    
    public SuggestWord() {
    }
    
    public SuggestWord(java.lang.String word) {
        this.word = word;
    }
    
    public java.lang.String getWord() {
        return word;
    }
    
    public void setWord(java.lang.String word) {
        this.word = word;
    }
}
