// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws637;


public class SuggestWordResponse {
    protected java.lang.String suggestWordResult;
    
    public SuggestWordResponse() {
    }
    
    public SuggestWordResponse(java.lang.String suggestWordResult) {
        this.suggestWordResult = suggestWordResult;
    }
    
    public java.lang.String getSuggestWordResult() {
        return suggestWordResult;
    }
    
    public void setSuggestWordResult(java.lang.String suggestWordResult) {
        this.suggestWordResult = suggestWordResult;
    }
}
