// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.jbws637;


public class Words {
    protected java.lang.String[] suggestions;
    protected java.lang.String word;
    protected int suggestionCount;
    
    public Words() {
    }
    
    public Words(java.lang.String[] suggestions, java.lang.String word, int suggestionCount) {
        this.suggestions = suggestions;
        this.word = word;
        this.suggestionCount = suggestionCount;
    }
    
    public java.lang.String[] getSuggestions() {
        return suggestions;
    }
    
    public void setSuggestions(java.lang.String[] suggestions) {
        this.suggestions = suggestions;
    }
    
    public java.lang.String getWord() {
        return word;
    }
    
    public void setWord(java.lang.String word) {
        this.word = word;
    }
    
    public int getSuggestionCount() {
        return suggestionCount;
    }
    
    public void setSuggestionCount(int suggestionCount) {
        this.suggestionCount = suggestionCount;
    }
}
